- components/dmesg/config.go
- components/query/log/tail/options.go
- components/query/log/tail/streamer_command.go
`Commands [][]string` run in sequence, so in case `-w` is not supported in some machines, we should continue to the next commands.
> log.Logger.Debugw("command was terminated (exit code -1) by the root context cancellation", "cmd", sr.cmd.String(), "contextError", sr.ctx.Err())
to clarify the logging (this is expected when we run `gpud down`)
Previous logging was confusing:
> {"level":"warn","ts":"2024-08-19T18:20:17Z","caller":"tail/streamer_command.go:138","msg":"error waiting for command to finish","error":"signal: terminated","cmd":"/usr/bin/bash /tmp/streamer-from-command2548997474.txt"}
{"level":"warn","ts":"2024-08-19T18:27:11Z","caller":"tail/streamer_command.go:138","msg":"error waiting for command to finish","error":"signal: terminated","cmd":"/usr/bin/bash …
> fix(dmesg): add fallback dmesg watch command, remove confusing log message

- pkg/systemd/systemd.go
Fix the following error:
```
exit status 3
```
> fix(systemd): handle exit status for "gpud status" command when gpud is inactive

- components/diagnose/diagnose.go
- components/dmesg/config.go
- components/query/log/tail/options.go
- components/query/log/tail/scan.go
- components/query/log/tail/streamer_command.go
- config/default.go
- pkg/process/options.go
- pkg/process/process.go
- pkg/process/process_test.go
We run external commands as an external process within gpud everything (e.g., dmesg, dmesg -w, gpud diagnosis for nvidia* commands). We should have a shared package that runs those commands. (optiona) Will be useful for next phase of GPUd where we can maintain the on-host components.
> feat(pkg/process): initial commit, fix dmesg scan on non-root

- components/fd/component_output.go
This shouldn't fail the whole `getUsage` function:
> stat /proc/1321147/fd: no such process
> fix(components/fd): skip error if descriptor file is deleted

- components/accelerator/nvidia/query/nvidia_peermem.go
- pkg/process/process_test.go
Tested and worked:
```
fabric_manager:
active: true
version: 535.161.08
fabric_manager_exists: true
ibstat:
raw: ""
ibstat_exists: true
infiniband_class_exists: true
lsmod_peermem:
ibcore_using_peermem_module: true
ibstat_exists: true
infiniband_class_exists: true
raw: |-
nvidia_peermem         16384  0
ib_core               434176  9 rdma_cm,ib_ipoib,nvidia_peermem,iw_cm,ib_umad,rdma_ucm,ib_uverbs,mlx5_ib,ib_cm
nvidia              56717312  550 nvidia_uvm,nvidia_peermem,nvidia_modeset
```
> feat(nvidia/query): check lsmod output with retries

- cmd/gpud/command/down.go
Before:
```
gpud down
✘ failed to stop systemd unit 'gpud.service': systemctl stop failed: exit status 5 output: Failed to stop gpud.service: Unit gpud.service not loaded.
gpud: systemctl stop failed: exit status 5 output: Failed to stop gpud.service: Unit gpud.service not loaded.
```
After:
```
gpud down
✔ gpud is not running (no-op)
```
> fix(cmd/gpud): clean up "gpud down" logs

- Makefile
- docs/ARCHITECTURE.md
- docs/COMPONENTS.md
Fix invalid document links, delete invalid document content, and add `CGO_ENABLED=1` configuration when compiling `gpud` in Makefile.
> fix(docs): pkg.go.dev links, add Makefile CGO_ENABLED=1

- components/accelerator/nvidia/clock/component_output.go
- components/accelerator/nvidia/query/nvml/clock_events.go
- components/accelerator/nvidia/query/nvml/nvml.go
- components/accelerator/nvidia/query/nvml/nvml_test.go
- components/accelerator/nvidia/query/query.go
- config/default.go
Reported by @cardyok:
Not all NVIDIA drivers support this symbol. And if we don't do this, the CGO call just exits the whole process.
(ref. https://github.com/NVIDIA/go-nvml/pull/123)
> fix(nvidia): skip clock events NVML check if not supported by old drivers

- components/fd/component_output.go
- components/fd/component_output_test.go
- components/fd/config.go
- components/fd/metrics/metrics.go
- internal/server/server.go
We should not use rlimit since it's specific to the process (in this case, fd limit for the gpud process).
> fix(components/fd): use system-wide file descriptor limit, add default 1-million threshold limit, remove "_avg" metrics in fd component

- components/accelerator/nvidia/query/query.go
Fix
```
⌛ scanning nvidia accelerators
{"level":"warn","ts":"2024-09-08T04:35:57Z","caller":"nvml/nvml.go:322","msg":"gpm metrics not supported"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc414e2]
goroutine 1 [running]:
github.com/leptonai/gpud/components/accelerator/nvidia/query.Get({0x19b3a18, 0xc000880850})
/home/ubuntu/leptonai/gpud/components/accelerator/nvidia/query/query.go:106 +0x7c2
github.com/leptonai/gpud/components/diagnose.Scan({0x19b3a18, 0xc000880850}, {0xc0000537b8, 0x4, 0xc0000536b0?})
/home/ubuntu/leptonai/gpud/components/diagnose/scan.go:42 +0x214
github.com/leptonai/gpud/cmd/gpud/command.cmdScan(0xc000336440?)
/home/ubuntu/leptonai/gpud/cmd/gpud/command/scan.go:15 +0xff …
```
> fix(accelerator/nvidia): panic when ibstat command fails, when recording errors

- components/accelerator/nvidia/gpm/component_output.go
```json
{
"component": "accelerator-nvidia-gpm",
"states": [
{
"name": "gpm",
"healthy": true,
"extra_info": {
"data": "{}",
"encoding": "json"
}
}
]
},
```
> fix(accelerator/nvidia/gpm): add missing Healthy: true field

- components/dmesg/filters.go
- components/dmesg/filters_test.go
e.g.,
> Aug 30 06:58:55.050705 ... kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=cri-containerd-ec9ee26695deb4cc72bc665efff1cf3a03fdfb12f1303e02fe9252985e084a95.scope,mems_allowed=0-1,oom_memcg=/lxc.payload....-lxc/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podeded8c65_6e8e_4c6e_a889_3e427565c740.slice,task_memcg=/lxc.payload.ny2g2r5hh3-lxc/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podeded8c65_6e8e_4c6e_a889_3e427565c740.slice/cri-containerd-ec9ee26695deb4cc72bc665efff1cf3a03fdfb12f1303e02fe9252985e084a95.scope,task=pt_main_thread,pid=461754,uid=0
> feat(dmesg): add oom-kill:constraint regex for cri-containerd events

- components/accelerator/nvidia/info/component_output.go
- components/accelerator/nvidia/memory/component_output.go
- components/accelerator/nvidia/peermem/component_output.go
- components/accelerator/nvidia/query/gpu_memory.go
- components/accelerator/nvidia/query/gpu_memory_test.go
- components/accelerator/nvidia/query/metrics/remapped-rows/metrics.go
- components/accelerator/nvidia/query/nvidia_smi_query_gpu.go
- components/accelerator/nvidia/query/nvidia_smi_query_test.go
- components/accelerator/nvidia/query/nvml/clock_speed.go
- components/accelerator/nvidia/query/nvml/ecc_errors.go
- components/accelerator/nvidia/query/nvml/nvml.go
- components/accelerator/nvidia/query/nvml/remapped_rows.go
- components/accelerator/nvidia/query/query.go
- components/accelerator/nvidia/query/testdata/nvidia-smi-query.535.129.03.out.0.valid.a10
- components/accelerator/nvidia/remapped-rows/component.go
- components/accelerator/nvidia/remapped-rows/component_output.go
- components/accelerator/nvidia/remapped-rows/config.go
- config/default.go
- docs/COMPONENTS.md
- internal/server/server.go
This should alert, since this GPU requires a reset to actually remap the rows:
```
Remapped Rows
Correctable Error                 : 0
Uncorrectable Error               : 4
Pending                           : Yes
```
ref. https://docs.nvidia.com/deploy/a100-gpu-mem-error-mgmt/index.html
> feat(nvidia): track row remapping, RMA/GPU reset status

- components/accelerator/nvidia/ecc/component_output.go
- components/accelerator/nvidia/ecc/component_output_test.go
- components/accelerator/nvidia/query/nvidia_smi_query_gpu.go
- components/accelerator/nvidia/query/nvidia_smi_query_test.go
- components/accelerator/nvidia/query/nvml/ecc_errors.go
- components/accelerator/nvidia/query/nvml/ecc_mode.go
- components/accelerator/nvidia/query/nvml/nvml.go
Especially, `nvmlDeviceGetMemoryErrorCounter` requires "ECC mode" to be enabled.
See https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g30900e951fe44f1f952f0e6c89b0e2c1.
> feat(nvidia): track "ECC mode" (enabled/disabled) using nvidia-smi and NVML

- components/accelerator/nvidia/ecc/component.go
- components/accelerator/nvidia/ecc/component_output.go
- components/accelerator/nvidia/ecc/component_output_test.go
- docs/COMPONENTS.md
https://github.com/leptonai/gpud/pull/86 is now tracking "ECC Mode", regardless of its error counts.
Thus, renaming the state key to "ecc", not "ecc-errors".
> feat(nvidia/ecc): rename state name key to "ecc" (from ecc_errors)

- components/accelerator/nvidia/ecc/component_output.go
- components/accelerator/nvidia/ecc/component_output_test.go
- components/accelerator/nvidia/query/nvml/ecc_errors.go
> when an uncorrectable ECC error is detected, the NVIDIA driver software will perform error recovery.
Meaning, as long as NVIDIA performs row remapping, we don't need to mark this unhealthy. Instead, we monitor remapping-rows component for potential system reboot or gpu reset suggested actions
ref. https://docs.nvidia.com/deploy/a100-gpu-mem-error-mgmt/index.html
Fix
> fix(components/accelerator-nvidia-ecc): do not unhealthy when driver recovers uncorrectable ecc errors

- components/accelerator/nvidia/infiniband/component_output.go
- components/accelerator/nvidia/query/ibstat.go
- components/accelerator/nvidia/query/ibstat_test.go
Should not happen... but in case our hard-coded ibstat "State" string match fails (e.g., breaking API changes), we fallback to "Physical state" for link status checking.
```
CA 'mlx5_8'
CA type: MT4125
Number of ports: 1
Firmware version: 22.39.1002
Hardware version: 0
Node GUID: 0xe8ebd303003307df
System image GUID: 0xe8ebd303003307de
Port 1:
State: Down
Physical state: Disabled
```
> feat(nvidia/ibstat): check "Physical state" as fallback

- cmd/gpud/command/accelerator.go
- cmd/gpud/command/command.go
- components/accelerator/detect.go
- components/accelerator/nvidia/query/nvidia_smi_query.go
```
gpud -h
NAME:
gpud -
gpud scan
sudo gpud up
USAGE:
gpud [global options] command [command options] [arguments...]
VERSION:
a1f836a
DESCRIPTION:
monitor your GPU/CPU machines and run workloads
COMMANDS:
login           login gpud to lepton.ai (called automatically in gpud up with non-empty --token)
up              initialize and start gpud in a daemon mode (systemd)
down            stop gpud systemd unit
run             starts gpud without any login/checkin ('gpud up' is recommended for linux)
update          update gpud
release         release gpud
status, st      checks the status of gpud
logs, l         checks the gpud logs
accelerator, a  quick scans the currently installed accelerator
diagnose, d     collects diagnose information
scan, s         quick scans the host for any major …
```
> feat(components): add accelerator detect func, "gpud accelerator" subcommand

- internal/session/session.go
revert #7 
still need to close write channel, when control plane is restarting and 504 is thrown, http is disconnected and goroutine will be leak. There will be multiple consumers of s.writer and the old goroutine will keep consuming the data to be written back to control plane and control plane will never get response back.
> fix(session): close writer goroutine

- internal/session/serve.go
- pkg/reboot/reboot.go
To address issues like:
> [FIRING] reboot request failed for dedicated node group
Error: unexpected status code: 500,
body: {"message":"no active session for machine"} (read error: <nil>)
> feat(reboot): support optional delay reboot (reboot immediately by default)

- components/accelerator/nvidia/info/component_output.go
- components/accelerator/nvidia/query/device_count.go
- components/accelerator/nvidia/query/device_count_test.go
- components/accelerator/nvidia/query/query.go
Implementing `DCGM_FR_DEVICE_COUNT_MISMATCH` logic.
Tested
> ⌛ scanning nvidia accelerators
✔ successfully checked nvidia-smi
✔ GPU device count '8' (from /dev)
✔ GPU count '8' (from nvidia-smi)
✔ GPU count '8' (from NVML)
✔ GPU product name 'NVIDIA H100 80GB HBM3' (from nvidia-smi)
✔ GPU product name 'NVIDIA H100 80GB HBM3' (from NVML)
> feat(nvidia/info): report GPU device count from "/dev" (`DCGM_FR_DEVICE_COUNT_MISMATCH` DCGM)

- components/accelerator/nvidia/query/nvidia_smi_query.go
- components/accelerator/nvidia/query/xid/xid.go
nvidia-smi may get stuck with Xid 45, and in such case, the existing nvidia-smi may get stuck forever, when the nvidia-smi process goes into D (uninterruptible) state.
For example,
```
[Sat Oct 12 18:35:32 2024] NVRM: Xid (PCI:0000:61:00): 45, pid=1496200, name=distprovers-gpu, Ch 0000000a
[Sat Oct 12 18:35:32 2024] NVRM: Xid (PCI:0000:61:00): 45, pid=1496200, name=distprovers-gpu, Ch 0000000b
[Sat Oct 12 18:35:32 2024] NVRM: Xid (PCI:0000:61:00): 45, pid=1496200, name=distprovers-gpu, Ch 0000000c
[Sat Oct 12 18:35:32 2024] NVRM: Xid (PCI:0000:61:00): 45, pid=1496200, name=distprovers-gpu, Ch 0000000d
[Sat Oct 12 18:35:32 2024] NVRM: Xid (PCI:0000:61:00): 45, pid=1496200, name=distprovers-gpu, Ch 0000000e
[Sat Oct 12 18:35:32 2024] NVRM: Xid (PCI:0000:61:00): 45, pid=1496200, …
```
> fix(nvidia): suggest reboot for Xid 45, async nvidia-smi checks to not be stuck

- cmd/gpud/command/command.go
- cmd/gpud/command/run.go
- components/k8s/pod/component.go
- components/k8s/pod/component_output.go
- components/k8s/pod/component_test.go
- components/k8s/pod/config.go
- config/default.go
- config/op_options.go
- internal/server/server.go
> fix(k8s/pod): "gpud run --kubelet-ignore-connection-errors" to not mark unhealthy when read only port is not open (does not ignore by default)

- components/accelerator/nvidia/persistence-mode/component_output.go
Even if "nvidia-persistenced" is not running, GPU can have persistence mode enabled via NVML, thus we should not rely on nvidia-persistenced daemon running to decide whether the persistence mode is enabled or not.
Fix
Tested with 4090 machine
```
##################
NVML GPU-eeea5b9b-3ae5-3be8-ac2c-d26ab02b7899
✔ NVML persistence mode is enabled (nvidia-persistenced running false)
✔ NVML found no hw slowdown error
```
> fix(nvidia): persistence mode check based on NVML, do not rely on "nvidia-persistenced" binary

- components/components.go
- internal/server/server.go
Fix all the noisy logs
> {"level":"warn","ts":"2024-11-02T00:03:34Z","caller":"server/server.go:1040","msg":"failed to register component","name":"k8s-pod","error":"component k8s-pod already registered: already exists"}
{"level":"warn","ts":"2024-11-02T00:04:34Z","caller":"server/server.go:1040","msg":"failed to register component","name":"containerd-pod","error":"component containerd-pod already registered: already exists"}
{"level":"warn","ts":"2024-11-02T00:04:34Z","caller":"server/server.go:1040","msg":"failed to register component","name":"k8s-pod","error":"component k8s-pod already registered: already exists"}
{"level":"warn","ts":"2024-11-02T00:05:34Z","caller":"server/server.go:1040","msg":"failed to register component","name":"containerd-pod","error":"component containerd-pod …
> fix(components): do not attempt register if already registered

- cmd/gpud/main.go
- components/diagnose/diagnose.go
- components/diagnose/scan.go
- components/dmesg/config.go
- components/dmesg/filters.go
- components/dmesg/filters_nvidia.go
- config/default.go
When nvidia driver/device is broken, `gpud --version` blocks including others. This fixes the gpud initialization problem.
> strace gpud --version
Before
```
execve("/usr/sbin/gpud", ["gpud", "--version"], 0x7fff8bc31358 /* 24 vars */) = 0
brk(NULL)                               = 0x3b43000
rt_sigreturn({mask=[]})                 = 824646017024
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=220181, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 824646017024
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=220181, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 824646017024
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=220181, si_uid=0} ---
rt_sigreturn({mask=[]})                 = 824646017024
futex(0x315e7a0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
--- …
```
> fix(nvidia): remove init func for nvidia packages (do not check nvidia if not needed)

- components/accelerator/nvidia/query/nvml/xid.go
> {"level":"warn","ts":"2024-11-08T04:24:24Z","caller":"nvml/xid.go:170","msg":"notified xid event","event":{"time":"2024-11-08T04:24:24Z","sample_duration":"5s","device_uuid":"GPU-e3038df4-dc48-27c8-a48a-36956600f1c2","xid":0,"nvml_event_type":16,"nvml_event_type_single_bit_ecc_error":false,"nvml_event_type_double_bit_ecc_error":false,"nvml_event_type_p_state":false,"nvml_event_type_xid_critical_error":false,"nvml_event_type_clock":true,"nvml_event_type_power_source_change":false,"nvml_event_type_mig_config_change":false,"detail":null,"message":"received event but xid unknown"}}
> fix(nvidia/query): skip xid=0 event

- .custom-gcl.yml
- .github/workflows/golangci-lint.yml
- .golangci.yml
https://github.com/uber-go/nilaway
> level=info msg="golangci-lint has version v1.61.0-custom-gcl built with go1.23.1 from ? on 2024-11-09 05:32:32.785090935 +0000 UTC"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="Loaded : nilaway"
level=info msg="[lintersdb] Active 10 linters: [errcheck gofmt goimports gosimple govet ineffassign misspell staticcheck unconvert unused]"
> ci(github): run uber-go/nilaway

- components/diagnose/scan.go
- pkg/process/pids.go
We shouldn't see logs like these:
> {"level":"warn","ts":"2024-11-09T04:52:34Z","caller":"process/pids.go:35","msg":"failed to get status","error":"open /proc/2331227/status: no such file or directory"}
{"level":"warn","ts":"2024-11-09T04:52:34Z","caller":"process/pids.go:35","msg":"failed to get status","error":"open /proc/2331228/status: no such file or directory"}
{"level":"warn","ts":"2024-11-09T04:52:34Z","caller":"process/pids.go:35","msg":"failed to get status","error":"open /proc/2331232/status: no such file or directory"}
{"level":"warn","ts":"2024-11-09T04:52:34Z","caller":"process/pids.go:35","msg":"failed to get status","error":"open /proc/2337970/status: no such file or directory"}
{"level":"warn","ts":"2024-11-09T04:52:34Z","caller":"process/pids.go:35","msg":"failed to get …
> fix(pkg/process): skip without log for no such file

- components/systemd/component_output.go
- pkg/systemd/systemd.go
- pkg/systemd/systemd_test.go
> Error: failed to get uptime for unit kubelet: parsing time "n/a" as "Mon 2006-01-02 15:04:05 MST": cannot parse "n/a" as "Mon"
e.g.,
```
InactiveExitTimestamp=Fri 2024-11-08 03:20:47 UTC
InactiveExitTimestamp=Sat 2024-11-02 13:51:36 UTC
InactiveExitTimestamp=n/a
```
> fix(components/systemd): fix non-existing service uptime checks

- components/accelerator/nvidia/fabric-manager/config.go
- components/diagnose/diagnose.go
- components/diagnose/scan.go
- components/dmesg/component_event.go
- components/dmesg/component_state.go
- components/dmesg/component_test.go
- components/dmesg/filters.go
- components/dmesg/filters_nvidia.go
- components/query/log/common/common.go
- components/query/log/common/filter.go
- components/query/log/config/config.go
- components/query/log/poller.go
- components/query/log/tail/options.go
- components/query/log/tail/scan_test.go
- components/query/log/tail/streamer.go
- components/query/log/tail/streamer_command.go
> feat(components/query): move parse time func, filter to common packages

- components/accelerator/nvidia/error/sxid/component.go
- components/accelerator/nvidia/error/sxid/id/id.go
- components/accelerator/nvidia/error/xid/component.go
- components/accelerator/nvidia/error/xid/component_output.go
- components/accelerator/nvidia/error/xid/id/id.go
- components/dmesg/filters_nvidia.go
- config/default.go
- internal/server/dependency.go
- internal/server/server.go
Useful to implement xid/sxid persistency layer, to avoid circular dependencies.
> feat(components/nvidia): separate id packages for xid, sxid

- components/accelerator/nvidia/query/sxid/dmesg.go
- components/accelerator/nvidia/query/xid/dmesg.go
- components/diagnose/diagnose.go
- components/diagnose/scan.go
- components/dmesg/poller.go
- pkg/dmesg/dmesg.go
- pkg/dmesg/dmesg_test.go
> feat(pkg/dmesg): use common ctime parser

- cmd/gpud/command/logs.go
- components/diagnose/diagnose.go
- components/diagnose/scan.go
- components/dmesg/component.go
- components/query/log/tail/options.go
- components/query/log/tail/scan.go
- components/query/log/tail/scan_benchmark_test.go
- components/query/log/tail/scan_test.go
There's no reason to catch all these logs with same timestamps:
> [Thu Sep 19 02:29:46 2024] nvidia-peermem nv_get_p2p_free_callback:127 ERROR detected invalid context, skipping further processing
> [Thu Sep 19 02:29:46 2024] nvidia-peermem nv_get_p2p_free_callback:127 ERROR detected invalid context, skipping further processing
> [Thu Sep 19 02:29:46 2024] nvidia-peermem nv_get_p2p_free_callback:127 ERROR detected invalid context, skipping further processing
> feat(tail/log): dedup same log string in scanner

- components/dmesg/config.go
Which makes wrong event detection with inconsistent timestamps than dmesg --ctime outputs:
> [1105056.784211] kernel: nvidia-peermem nv_get_p2p_free_callback:127 ERROR detected invalid context, skipping further processing
[1105056.804136] kernel: nvidia-peermem nv_get_p2p_free_callback:127 ERROR detected invalid context, skipping further processing
[1105056.824136] kernel: nvidia-peermem nv_get_p2p_free_callback:127 ERROR detected invalid context, skipping further processing
> fix(components/dmesg): do not read raw dmesg file with unix time

- components/os/component_test.go
- components/query/log/poller.go
- components/query/log/tail/streamer.go
- components/query/log/tail/streamer_command.go
- components/query/log/tail/streamer_command_test.go
- components/query/log/tail/streamer_file.go
- components/query/log/tail/streamer_file_test.go
Will be useful to dedup the same messages from dmesg:
> feat(query/log/tail): log stream with deduper

- components/accelerator/nvidia/infiniband/component.go
- components/accelerator/nvidia/infiniband/component_output.go
- components/accelerator/nvidia/infiniband/component_output_test.go
- components/accelerator/nvidia/infiniband/config.go
- components/accelerator/nvidia/infiniband/config_test.go
- components/accelerator/nvidia/peermem/component_output.go
- components/accelerator/nvidia/query/infiniband/infiniband.go
- components/accelerator/nvidia/query/infiniband/infiniband_test.go
- components/accelerator/nvidia/query/infiniband/parse.go
- components/accelerator/nvidia/query/infiniband/parse_test.go
- components/accelerator/nvidia/query/infiniband/testdata/ibstat.47.0.all.active.0
- components/accelerator/nvidia/query/infiniband/testdata/ibstat.47.0.all.active.1
- components/accelerator/nvidia/query/infiniband/testdata/ibstat.47.0.some.down.0
- components/accelerator/nvidia/query/infiniband/testdata/ibstat.47.0.some.down.1
- components/accelerator/nvidia/query/peermem/peermem.go
- components/accelerator/nvidia/query/peermem/peermem_test.go
- components/accelerator/nvidia/query/query.go
- internal/server/server.go
To handle the machines with
```
CA 'mlx5_2'
CA type: MT4125
Number of ports: 1
Firmware version: 22.38.1002
Hardware version: 0
Node GUID: 0x946dae0300c2b691
System image GUID: 0x946dae0300c2b690
Port 1:
State: Down
Physical state: Disabled
Rate: 40
Base lid: 0
```
> feat(nvidia): parse infiniband ibstat for error checking based on GPU card counts

- components/systemd/component_output.go
- pkg/systemd/systemd.go
To handle the case with trailing "\x0a"
Fix
> Error: failed to get uptime for unit network.target: parsing time "n/a" as "Mon 2006-01-02 15:04:05 MST": cannot parse "n/a" as "Mon"
> fix(pkg/systemd): handle "n/a" in uptime with trailing characters

- components/k8s/pod/component_output.go
> connection error to node  -- Get "http://localhost:10255/pods": dial tcp [::1]:10255: connect: connection refused
should be
> connection error to node "" -- Get "http://localhost:10255/pods": dial tcp [::1]:10255: connect: connection refused
> nit(k8s/pod): quote string node name in case it's empty

- components/accelerator/nvidia/fabric-manager/component_test.go
- components/accelerator/nvidia/query/fabric-manager-log/poller_test.go
- components/query/log/poller.go
- components/query/log/tail/options.go
- components/query/log/tail/streamer_command.go
- components/query/log/tail/streamer_file.go
- components/query/log/tail/streamer_file_test.go
- components/query/log/tail/testdata/fabric-manager.0.log
The "tail" library emits the existing lines in the file, when we spawn the tail-er on a file, thus requires custom log line time parser function (e.g., fabric manager log)
Fix where the following "old" logs show up in our fabric manager component events:
> {"fabricmanager_nvswitch_log_error":"","fabricmanager_nvswitch_log_filter":"{\"name\":\"accelerator-nvidia-fabric-manager-nvlink-failure\",\"regex\":\".+failed to find the GPU handle \\\\d+ in the multicast team .*\",\"owner_references\":[\"accelerator-nvidia-fabric-manager\"]}","fabricmanager_nvswitch_log_line":"[Apr 17 2024 01:51:39] [ERROR] [tid 2999877] failed to find the GPU handle 10187860174420860981 in the multicast team request setup 5653964288847403984.","fabricmanager_nvswitch_log_unix_seconds":"1734654883"}
> fix(query/log/tail): fix time parser for initial lines, use correct time for fabric manager /events

- components/accelerator/nvidia/query/xid-sxid-state/options.go
- components/accelerator/nvidia/query/xid-sxid-state/state.go
- components/accelerator/nvidia/query/xid-sxid-state/state_test.go
Preparing the code cleanups in xid and sxid components:
1. switch to this shared database to query the latest xid/sxid events
2. remove redundant polling logic in xid + sxid components
3. remove xid-sxid component
> feat(nvidia/xid, sxid): support query by event type

- components/accelerator/nvidia/bad-envs/component.go
- components/accelerator/nvidia/clock-speed/component.go
- components/accelerator/nvidia/ecc/component.go
- components/accelerator/nvidia/error/component.go
- components/accelerator/nvidia/error/sxid/component_output.go
- components/accelerator/nvidia/error/xid/component.go
- components/accelerator/nvidia/error/xid/component_output.go
- components/accelerator/nvidia/fabric-manager/component.go
- components/accelerator/nvidia/gpm/component.go
- components/accelerator/nvidia/gsp-firmware-mode/component.go
- components/accelerator/nvidia/infiniband/component.go
- components/accelerator/nvidia/info/component.go
- components/accelerator/nvidia/memory/component.go
- components/accelerator/nvidia/nvlink/component.go
- components/accelerator/nvidia/peermem/component.go
- components/accelerator/nvidia/persistence-mode/component.go
- components/accelerator/nvidia/power/component.go
- components/accelerator/nvidia/power/id/id.go
- components/accelerator/nvidia/processes/component.go
- components/accelerator/nvidia/query/nvml/gpm.go
- components/accelerator/nvidia/query/query.go
- components/accelerator/nvidia/remapped-rows/component.go
- components/accelerator/nvidia/temperature/component.go
- components/accelerator/nvidia/utilization/component.go
- components/query/poller.go
- components/query/poller_test.go
- config/default.go
- internal/server/handlers_root.go
- internal/server/server.go
If one operation fails, the shared poller should still return the data so that each component that consumes the shared data can evaluate their own healthiness.
> feat(nvidia): use last successful data in shared poller, shared nvidia-smi/nvml poller to still return data if one operation fails

- components/accelerator/nvidia/query/nvidia_smi_query.go
- components/accelerator/nvidia/query/query.go
So, we can go back to the successful one
> fix(nvidia/query): poller to return error on nvidia-smi failure

- pkg/disk/disk.go
```
partitions have total mounted size 141 TB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe6be70]
goroutine 1 [running]:
github.com/leptonai/gpud/pkg/disk.Partitions.RenderTable({0xc000451508, 0xf, 0x1a2ae96?}, {0x1c97080?, 0xc00019c038?})
/home/runner/work/gpud/gpud/pkg/disk/disk.go:132 +0x1d0
github.com/leptonai/gpud/components/diagnose.Scan({0x1cae600, 0xc000701c00}, {0xc0000537b0, 0x5, 0x0?})
/home/runner/work/gpud/gpud/components/diagnose/scan.go:281 +0x1538
github.com/leptonai/gpud/cmd/gpud/command.cmdScan(0xc0006bc120?)
/home/runner/work/gpud/gpud/cmd/gpud/command/scan.go:40 +0x337
github.com/urfave/cli.HandleAction({0x1734200?, 0x1aeaf18?}, 0x4?) …
```
> fix(pkg/disk): skip usage table output render if unmounted

- components/accelerator/nvidia/peermem/component.go
- components/accelerator/nvidia/peermem/component_test.go
- components/accelerator/nvidia/query/peermem/dmesg.go
- components/accelerator/nvidia/query/peermem/dmesg_test.go
as the latest driver fixes the issue
ref. https://github.com/Mellanox/nv_peer_memory/issues/120
> feat(nvidia/peermem): explicitly skip "invalid context" errors

- cmd/gpud/command/run.go
- components/state/state.go
- components/state/state_test.go
- config/config.go
- config/config_test.go
- config/default.go
- internal/server/server.go
To help with
```
goroutine 170 [select, 1350 minutes]:
database/sql.(*DB).connectionOpener(0xc001004340, {0x1cae590, 0xc0008fc5f0})
/opt/hostedtoolcache/go/1.23.3/x64/src/database/sql/sql.go:1253 +0x87
created by database/sql.OpenDB in goroutine 1
/opt/hostedtoolcache/go/1.23.3/x64/src/database/sql/sql.go:833 +0x130
goroutine 194 [select]:
github.com/leptonai/gpud/internal/server.New.func2()
/home/runner/work/gpud/gpud/internal/server/server.go:204 +0xc5
created by github.com/leptonai/gpud/internal/server.New in goroutine 1
/home/runner/work/gpud/gpud/internal/server/server.go:201 +0xa57
goroutine 196 [select, 90 minutes]:
github.com/leptonai/gpud/internal/server.New.func3()
/home/runner/work/gpud/gpud/internal/server/server.go:227 +0xba
created by …
```
> feat(server): vacuum sqlite only once a week

- cmd/gpud/command/join.go
- components/accelerator/nvidia/query/detect.go
- components/accelerator/nvidia/query/infiniband/infiniband.go
- components/accelerator/nvidia/query/nvidia_smi_query.go
- components/accelerator/nvidia/query/peermem/peermem.go
- components/diagnose/diagnose.go
- components/dmesg/config.go
- components/query/log/tail/scan.go
- components/query/log/tail/streamer_command.go
- manager/controllers/package_controller.go
- pkg/disk/findmnt.go
- pkg/disk/lsblk.go
- pkg/host/machine_id.go
- pkg/host/virt.go
- pkg/pci/pci.go
- pkg/process/examples/bash-script-output-to-file/main.go
- pkg/process/examples/restart-commands/main.go
- pkg/process/examples/simple-command/main.go
- pkg/process/examples/simple-commands/main.go
- pkg/process/examples/stream-blocking-commands/main.go
- pkg/process/examples/stream-commands/main.go
- pkg/process/process.go
- pkg/process/process_test.go
- pkg/process/utils.go
- pkg/process/utils_test.go
- pkg/reboot/reboot.go
- pkg/systemd/journal.go
- pkg/systemd/systemd.go
Fix
> open /tmp/tmpbash888507873.bash: too many open files
> fix(*): add missing close on process that runs commands as bash, rename abort to close

- cmd/gpud/command/run.go
- components/accelerator/nvidia/query/clock-events-state/state.go
- components/accelerator/nvidia/query/xid-sxid-state/state.go
- components/fuse/state/state.go
- components/info/component.go
- components/info/component_test.go
- components/metrics/state/state.go
- components/pci/state/state.go
- components/query/log/state/state.go
- components/state/api_version.go
- components/state/boot_ids.go
- components/state/state.go
- config/config.go
- config/default.go
- internal/server/server.go
- pkg/sqlite/metrics.go
- pkg/sqlite/metrics_test.go
```json
"daemon_version": "v0.3.7",
"gpud_pid": "2301600",
"gpud_start_time_humanized": "1 minute ago",
"gpud_start_time_in_unix_time": "1737385595",
"gpud_usage_db_humanized": "10 MB",
"gpud_usage_db_in_bytes": "10244096",
"gpud_usage_delete_avg_latency_in_seconds": "0.000",
"gpud_usage_delete_avg_qps": "0.000",
"gpud_usage_delete_total": "0",
"gpud_usage_file_descriptors": "1056",
"gpud_usage_insert_update_avg_latency_in_seconds": "0.000",
"gpud_usage_insert_update_avg_qps": "64.639",
"gpud_usage_insert_update_total": "799",
"gpud_usage_memory_humanized": "224 MB",
"gpud_usage_memory_in_bytes": "224346112",
"gpud_usage_select_avg_latency_in_seconds": "0.009",
"gpud_usage_select_avg_qps": "31.713",
"gpud_usage_select_total": "392",
"mac_address": "74:50:4e:d3:48:98",
"packages": "null" …
```
> feat(sqlite): disable vacuum for now, bump up retention period, track latency, qps, expose via /info component

- components/accelerator/nvidia/hw-slowdown/state/options.go
- components/accelerator/nvidia/query/xid-sxid-state/options.go
- components/fuse/state/options.go
- components/pci/state/options.go
- components/state/boot_ids.go
- components/state/state.go
```
// Unix returns t as a Unix time, the number of seconds elapsed
// since January 1, 1970 UTC. The result does not depend on the
// location associated with t.
```
> feat(*): remove redundant utc call

- components/db/events.go
- components/db/events_benchmark_test.go
- components/db/events_test.go
- components/info/component.go
- components/state/state.go
- components/state/state_test.go
- internal/server/server.go
- pkg/sqlite/sqlite.go
Replace https://github.com/leptonai/gpud/pull/327.
Cherry-picked from https://github.com/leptonai/gpud/pull/321.
> feat(components/db): add common events store (similar to components.Event)

- components/diagnose/scan.go
- components/diagnose/scan_test.go
- pkg/dmesg/watcher.go
- pkg/dmesg/watcher_test.go
```
line kern  :err   : 2025-01-25T10:34:54,859532+00:00 nvidia-nvswitch1: SXid (PCI:0000:84:00.0): 12028, Data {0x000001c0, 0x00bd5c8a, 0x00000500, 0x00000064, 0x00000000, 0x40008000, 0x5a001100, 0x00000000, 0x00000000}
name: nvidia_nvswitch_sxid
owner_references:
- accelerator-nvidia-error-sxid
regex: 'SXid.*?: (\d+),'
{"level":"warn","ts":"2025-01-28T06:47:16Z","caller":"diagnose/scan.go:263","msg":"known sxid","line":"kern  :err   : 2025-01-25T10:34:54,859532+00:00 nvidia-nvswitch1: SXid (PCI:0000:84:00.0): 12028, Data {0x000001c0, 0x00bd5c8a, 0x00000500, 0x00000064, 0x00000000, 0x40008000, 0x5a001100, 0x00000000, 0x00000000}"}
detail:
always_fatal: false
critical_error_marked_by_gpud: true
description: ""
documentation_version: DU-09883-001_v1.3 (October 2023)
event_type: Fatal …
```
> fix(diagnose): scan to use "dmesg" with no time limit

- components/fd/component_output.go
- components/fd/component_output_test.go
To improve old message format:
> allocated_file_handles: 647456, allocated_percent: 0.00, running_pids: 2463, used_percent: 0.00; threshold_running_pids_percent is greater than 80
> feat(fd): improve reasons, human-readable

- components/accelerator/nvidia/query/nvml/options.go
- components/accelerator/nvidia/query/nvml/options_test.go
- components/accelerator/nvidia/query/options.go
- components/accelerator/nvidia/query/options_test.go
- components/accelerator/nvidia/query/query.go
- components/diagnose/scan.go
- internal/server/server.go
Replace https://github.com/leptonai/gpud/pull/341.
> feat(nvidia/query): pass events store to shared poller

- components/info/component.go
- pkg/sqlite/metrics.go
- pkg/sqlite/metrics_test.go
Fix the following output:
```json
"name": "daemon",
"healthy": true,
"reason": "daemon version: v0.3.7, mac address: c4:cb:e1:d2:4d:4e",
"extra_info": {
"daemon_version": "v0.3.7",
"gpud_pid": "1300055",
"gpud_start_time_humanized": "2 days ago",
"gpud_start_time_in_unix_time": "1738302894",
"gpud_usage_db_humanized": "39 MB",
"gpud_usage_db_in_bytes": "39202816",
"gpud_usage_delete_avg_latency_in_seconds": "0.1172523",
"gpud_usage_delete_avg_qps": "26.769",
"gpud_usage_delete_total": "39",
"gpud_usage_file_descriptors": "72",
"gpud_usage_insert_update_avg_latency_in_seconds": "0.0000957",
"gpud_usage_insert_update_avg_qps": "610163.653",
"gpud_usage_insert_update_total": "888951",
"gpud_usage_memory_humanized": "330 MB",
"gpud_usage_memory_in_bytes": "329768960", …
```
> fix(info): correctly compute GPUd sqlite metrics delta

- components/accelerator/nvidia/query/gpu_memory.go
- components/accelerator/nvidia/query/gpu_memory_test.go
- components/accelerator/nvidia/query/nvml/remapped_rows.go
- components/accelerator/nvidia/query/query.go
- components/accelerator/nvidia/remapped-rows/component_output.go
- components/accelerator/nvidia/remapped-rows/component_output_test.go
Fix
> nvidia-smi GPU GPU 00000000:E1:00.0 failed to determine if it qualifies for RMA: invalid remapping failure occurred value: "", GPU product name "NVIDIA GeForce RTX 4090" does not support row remapping (message: "GPU product name: \"NVIDIA GeForce RTX 4090\"
> fix(nvidia/remapped-rows): do not check row remapping for 4090 and other unsupported GPUs

- components/accelerator/nvidia/query/nvml/nvml.go
- components/accelerator/nvidia/query/nvml/nvml_test.go
> fix(nvml): parse driver version to handle the one without patch version

- pkg/dmesg/dmesg_test.go
- pkg/dmesg/watcher_test.go
> test(pkg/process): add more unit test cases

- components/db/events.go
- components/db/events_test.go
Address:
```
=== NAME  TestRetentionPurge
events_test.go:1378: 
Error Trace:	/home/runner/work/gpud/gpud/components/db/events_test.go:1378
Error:      	Not equal: 
expected: 1
actual  : 2
Test:       	TestRetentionPurge
{"level":"info","ts":"2025-02-10T10:17:41Z","caller":"db/events.go:160","msg":"closing the store","table":"test_table"}
{"level":"info","ts":"2025-02-10T10:17:41Z","caller":"db/events.go:154","msg":"purged data","table":"test_table","retention":10,"purged":1}
--- FAIL: TestRetentionPurge (2.01s)
```
> test(db/events): make retention purge unit tests less flaky

- internal/session/session.go
- internal/session/session_test.go
> tests(internal/session): add more unit tests with smaller functions

- go.mod
- go.sum
- pkg/dmesg/deduper.go
- pkg/dmesg/deduper_test.go
- pkg/dmesg/testdata/dmesg.peermem.log.0
- pkg/dmesg/watcher.go
- pkg/dmesg/watcher_test.go
- Deduplicate log lines if same second, same content
- Bump up dmesg log watcher channel buffer to 3,000
> feat(dmesg): dedup logs by seconds if same content, bump up log channel buffer

- pkg/latency/edge/derpmap/derp_regions.go
- pkg/latency/edge/derpmap/derpmap.json
```
+----------------+---------------+----------------+--------------+
|    PROVIDER    |  REGION NAME  |  REGION CODE   |   LATENCY    |
+----------------+---------------+----------------+--------------+
| tailscale-derp | Tokyo         | ap-northeast-1 | 42.579875ms  |
| tailscale-derp | Hong Kong     | ap-east-1      | 90.562042ms  |
| tailscale-derp | Singapore     | ap-southeast-1 | 90.938833ms  |
| tailscale-derp | San Francisco | us-west-1      | 136.052667ms |
| tailscale-derp | Los Angeles   | us-west-1      | 142.900166ms |
| tailscale-derp | Seattle       | us-west-2      | 151.225084ms |
| tailscale-derp | Dallas        | us-east-1      | 169.166667ms |
| tailscale-derp | Sydney        | ap-southeast-2 | 172.688417ms |
| tailscale-derp | Denver        | us-west-1      | …
```
> feat(network/edge/derpmap): add Ashburn (Virginia), Nuremberg (Germany)

- cmd/gpud/command/update.go
- cmd/gpud/command/update_test.go
Fix
> {"level":"info","ts":"2025-02-11T17:57:17-08:00","caller":"update/update.go:206","msg":"starting gpud update","version":"v0.4.2\n","url":"https://pkg.gpud.dev/","requireRoot":true,"useSystemd":true}
{"level":"info","ts":"2025-02-11T17:57:18-08:00","caller":"update/update.go:34","msg":"Downloading \"https://pkg.gpud.dev/gpud_v0.4.2%0A_linux_amd64_ubuntu24.04.tgz\""}
> feat(gpud update): trim space when fetching version from "_latest.txt"

- go.mod
- go.sum
> dep(go mod): bump up prom client go v.1.21.0

- pkg/session/serve.go
> nit(session): do not shadow component name var in metrics get within for-loops

- components/accelerator/nvidia/infiniband/component_test.go
- pkg/nvidia-query/infiniband/ibstat.go
- pkg/nvidia-query/infiniband/ibstat_test.go
- pkg/nvidia-query/infiniband/testdata/ibstat.47.0.h100.some.down.with.polling.1
To handle
```
CA 'mlx5_10'
CA type: MT4129
Number of ports: 1
Firmware version: 28.39.1002
Hardware version: 0
Node GUID: ...
System image GUID: ...
Port 1:
State: Down
Physical state: Polling
Rate: 10
Base lid: 868
LMC: 0
SM lid: 334
Capability mask: 0xa751e848
Port GUID: ...
Link layer: InfiniBand
```
> fix(infiniband): simplify port check message, handle "Polling" state

- e2e/e2e_test.go
- e2e/mock/nvml/instance_mock.go
Found it in https://github.com/leptonai/gpud/pull/491.
> fix(e2e): add missing shutdown, nvidia-smi input

- cmd/gpud/command/command.go
- cmd/gpud/command/scan.go
- components/memory/component.go
- pkg/diagnose/options.go
- pkg/diagnose/scan.go
- pkg/kmsg/kmsg.go
- pkg/kmsg/kmsg_test.go
- pkg/kmsg/testdata/kmsg.1.log
```
⌛ scanning kmsg
✔ scanned kmsg file -- found 4040 line(s)
✔ first kmsg line is 1 week ago old
```
to replace https://github.com/leptonai/gpud/pull/488 and address https://github.com/leptonai/gpud/issues/442.
Also close https://github.com/leptonai/gpud/issues/478.
c.f., https://github.com/euank/go-kmsg-parser
> feat(kmsg): initial commit (experiment to replace dmesg watcher)

- pkg/diagnose/scan.go
- pkg/kmsg/kmsg.go
```
⌛ scanning dmesg
[XID found] (54 minutes ago) "NVRM: Xid (PCI:0000:9b:00): 119, pid=4071838, name=python, Timeout after 45s of waiting for RPC response from GPU4 GSP! Expected function 76 (GSP_RM_CONTROL) (0x20801702 0x4)."
[XID found] (53 minutes ago) "NVRM: Xid (PCI:0000:9b:00): 119, pid=28232, name=cache_mgr_main, Timeout after 45s of waiting for RPC response from GPU4 GSP! Expected function 76 (GSP_RM_CONTROL) (0x20810108 0x3e0)."
[XID found] (52 minutes ago) "NVRM: Xid (PCI:0000:9b:00): 119, pid=28232, name=cache_mgr_main, Timeout after 45s of waiting for RPC response from GPU4 GSP! Expected function 76 (GSP_RM_CONTROL) (0x20803039 0x20)."
[XID found] (32 minutes ago) "NVRM: Xid (PCI:0000:9b:00): 119, pid=28098, name=gpu-feature-dis, Timeout after 45s of waiting for RPC response …
```
> fix(kmsg): fix uptime-based kmsg timestamp parsing

- pkg/diagnose/diagnose.go
- pkg/nvidia-query/detect.go
- pkg/nvidia-query/query.go
```
⌛ scanning nvidia accelerators
✔ found library libnvidia-ml.so at /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.535.216.03
✔ found library libcuda.so at /usr/lib/x86_64-linux-gnu/libcuda.so.535.216.03
```
> feat(nvidia): remove nvidia-smi dependency in all places (use NVML instead)

- e2e/mock/nvml/instance_mock.go
To fix
```
{"level":"info","ts":"2025-03-11T06:09:41Z","caller":"nvml/nvml.go:243","msg":"getting driver version from nvml library"}
panic: Interface.SystemGetCudaDriverVersion_v2Func: method is nil but Interface.SystemGetCudaDriverVersion_v2 was just called
goroutine 1 [running]:
github.com/NVIDIA/go-nvml/pkg/nvml/mock.(*Interface).SystemGetCudaDriverVersion_v2(0x2aa0ac0?)
/home/runner/go/pkg/mod/github.com/!n!v!i!d!i!a/go-nvml@v0.12.4-1/pkg/nvml/mock/interface.go:13299 +0xe5
github.com/leptonai/gpud/pkg/nvidia-query/nvml.GetCUDAVersion()
/home/runner/work/gpud/gpud/pkg/nvidia-query/nvml/nvml.go:203 +0x48
github.com/leptonai/gpud/pkg/nvidia-query/nvml.NewInstance({0x1deb870, 0xc00057dd50}, {0xc00005aac8, 0x2, 0x2})
/home/runner/work/gpud/gpud/pkg/nvidia-query/nvml/nvml.go:252 +0x29f …
```
> fix(e2e): add missing get cuda version nvml call mock

- components/accelerator/nvidia/sxid/component.go
- components/accelerator/nvidia/xid/component.go
multiple xid might happen at same timestamp, add a rand millisecond to event timestamp to avoid conflict
> fix(xid/sxid): add rand millisecond to event timestamp to avoid conflict

- components/os/component_output.go
- components/os/component_output_test.go
- pkg/nvidia-query/query.go
> feat(os, peermem): ignore lsmod, system virt cmd timeouts (as non-actionable)

- components/cpu/metrics/metrics.go
- components/disk/metrics/metrics.go
- components/memory/metrics/metrics.go
- pkg/gpud-metrics/averager.go
- pkg/gpud-metrics/averager_test.go
- pkg/gpud-metrics/state/state.go
- pkg/gpud-metrics/state/state_test.go
- pkg/nvidia-query/metrics/clock-speed/metrics.go
- pkg/nvidia-query/metrics/memory/metrics.go
- pkg/nvidia-query/metrics/power/metrics.go
- pkg/nvidia-query/metrics/temperature/metrics.go
- pkg/nvidia-query/metrics/utilization/metrics.go
Fault-prone...
```
unexpected fault address 0x6304e55848a6b
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6304e55848a6b pc=0x4247c1]
goroutine 307 gp=0xc0004fb6c0 m=42 mp=0xc001b1b108 [running]:
runtime.throw({0x1b12994?, 0x7c47e5b223c8?})
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/panic.go:1067 +0x48 fp=0xc001540e30 sp=0xc001540e00 pc=0x48bac8
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/signal_unix.go:931 +0x26c fp=0xc001540e90 sp=0xc001540e30 pc=0x48dd6c
runtime.buildTypeAssertCache.func1(...)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:532
runtime.buildTypeAssertCache(0x18d96c0?, 0x18d9940, 0x7c479d9bae28)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:544 +0x141 fp=0xc001540ed8 sp=0xc001540e90 pc=0x4247c1 …
```
> feat(metrics): remove unused EMA sql track/query

- pkg/nvidia-query/nvml/error.go
- pkg/nvidia-query/nvml/error_test.go
- pkg/nvidia-query/nvml/processes.go
To address:
>,"caller":"nvidia-query/query.go:159","msg":"nvml get failed","error":"failed to get process 130925 utilization: ERROR_NOT_FOUND (GPU uuid GPU-871a1068-5809-c0c4-5286-7b06ef9fc3e3)\nfailed to get process 130925 utilization: ERROR_NOT_FOUND (GPU uuid GPU-305d4b1a-067c-7fe2-efc5-e8d0df2036ba)"}
> fix(nvidia): handle nvml.ERROR_NOT_FOUND in utilization query

- components/accelerator/nvidia/processes/component_output.go
- components/accelerator/nvidia/processes/component_output_test.go
To help address:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6534f1]
goroutine 93521 [running]:
encoding/json.(*encodeState).marshal.func1()
/opt/hostedtoolcache/go/1.23.6/x64/src/encoding/json/encode.go:294 +0x6d
panic({0x18caaa0?, 0x2ace010?})
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/panic.go:785 +0x132
encoding/json.addrMarshalerEncoder(0xc002b4a740, {0x1adb180?, 0xc001562e48?, 0xc001d30400?}, {0x76?, 0x0?})
/opt/hostedtoolcache/go/1.23.6/x64/src/encoding/json/encode.go:460 +0x151
encoding/json.condAddrEncoder.encode({0x1c3d598?, 0x1c3d5e0?}, 0x54e0a8?, {0x1adb180?, 0xc001562e48?, 0xc001562e28?}, {0xe?, 0x0?})
/opt/hostedtoolcache/go/1.23.6/x64/src/encoding/json/encode.go:902 +0x44 …
```
> fix(nvidia/processes): handle nil output/data for /states response

- pkg/eventstore/database.go
- pkg/eventstore/database_test.go
To help address:
```
unexpected fault address 0x630973f0815ea
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x630973f0815ea pc=0x4247c1]
goroutine 394 gp=0xc001a70e00 m=49 mp=0xc001e34708 [running]:
runtime.throw({0x1b1a72d?, 0x796932e8a9d8?})
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/panic.go:1067 +0x48 fp=0xc001f43268 sp=0xc001f43238 pc=0x48bac8
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/signal_unix.go:931 +0x26c fp=0xc001f432c8 sp=0xc001f43268 pc=0x48dd6c
runtime.buildTypeAssertCache.func1(...)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:532
runtime.buildTypeAssertCache(0x18e56e0?, 0x18e5860, 0x7968eacc4998)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:544 +0x141 fp=0xc001f43310 sp=0xc001f432c8 pc=0x4247c1 …
```
> feat(eventstore): handle invalid sql conversion error better

- pkg/gpud-metrics/state/state.go
- pkg/gpud-metrics/state/state_test.go
To help debug:
```
unexpected fault address 0x630ccf4982166
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x630ccf4982166 pc=0x4247c1]
goroutine 318 gp=0xc0006848c0 m=8 mp=0xc000600008 [running]:
runtime.throw({0x1b1dbc5?, 0x79ff8aa98a68?})
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/panic.go:1067 +0x48 fp=0xc002e4b0a0 sp=0xc002e4b070 pc=0x48bac8
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/signal_unix.go:931 +0x26c fp=0xc002e4b100 sp=0xc002e4b0a0 pc=0x48dd6c
runtime.buildTypeAssertCache.func1(...)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:532
runtime.buildTypeAssertCache(0x18e8180?, 0x18e8400, 0x79ff4334d228)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:544 +0x141 fp=0xc002e4b148 sp=0xc002e4b100 pc=0x4247c1 …
```
> fix(metrics/state): fix select query on empty secondaryName

- go.mod
> go.mod: bump up go version to 1.23.7

- components/accelerator/nvidia/nvlink/component.go
- pkg/nvidia-query/metrics/nvlink/metrics.go
- pkg/nvidia-query/nvml/nvlink.go
- pkg/nvidia-query/nvml/nvlink_test.go
- pkg/nvidia-query/query.go
During testing, it was found that gpud would panic randomly at any place, and the stack would point to the same place:
```go
runtime.throw({0x24db382?, 0xc0027c0808?})
/usr/local/go/src/runtime/panic.go:1101 +0x48 fp=0xc002b122a0 sp=0xc002b12270 pc=0x497dc8
/usr/local/go/src/runtime/signal_unix.go:939 +0x1e5 fp=0xc002b122d0 sp=0xc002b122a0 pc=0x49a365
runtime.buildTypeAssertCache.func1(0x88?, 0x0?)
/usr/local/go/src/runtime/iface.go:532 +0xc fp=0xc002b122f0 sp=0xc002b122d0 pc=0x42f14c
runtime.buildTypeAssertCache(0x24db33c?, 0x219d380, 0x0)
/usr/local/go/src/runtime/iface.go:544 +0x1aa fp=0xc002b12370 sp=0xc002b122f0 pc=0x42f0ca
runtime.typeAssert(0x321c630, 0x219d380)
/usr/local/go/src/runtime/iface.go:497 +0xae fp=0xc002b123a8 sp=0xc002b12370 pc=0x42ee6e
```
We all …
> fix: panic on special environments

- go.mod
> go.mod: bump up go version to 1.24.1

- .github/workflows/tests-e2e.yml
- cmd/gpud/command/command.go
- cmd/gpud/command/run.go
- components/cpu/metrics/metrics.go
- components/disk/metrics/metrics.go
- components/fuse/metrics/metrics.go
- components/memory/metrics/metrics.go
- components/network/latency/metrics/metrics.go
- e2e/e2e_test.go
- pkg/config/config.go
- pkg/metrics/scraper/prometheus.go
- pkg/metrics/scraper/prometheus_test.go
- pkg/metrics/store/sqlite.go
- pkg/metrics/store/sqlite_test.go
- pkg/metrics/syncer/syncer.go
- pkg/metrics/syncer/syncer_test.go
- pkg/metrics/type.go
- pkg/metrics/utils.go
- pkg/metrics/utils_test.go
- pkg/server/handlers.go
- pkg/server/handlers_components.go
- pkg/server/server.go
```
disk_free_bytes{gpud_component="disk",gpud_metric_label="/"} 2.407153664e+10
disk_last_update_unix_seconds 1.743255649e+09
disk_total_bytes{gpud_component="disk",gpud_metric_label="/"} 7.6887154688e+10
disk_used_bytes{gpud_component="disk",gpud_metric_label="/"} 5.2798840832e+10
disk_used_bytes_avg{gpud_component="disk",gpud_metric_label="/",last_period="5m0s"} 5.2745824256e+10
disk_used_bytes_percent{gpud_component="disk",gpud_metric_label="/"} 68.6855490611[216](https://github.com/leptonai/gpud/actions/runs/14146180195/job/39633738807?pr=577#step:5:217)9
disk_used_bytes_percent_avg{gpud_component="disk",gpud_metric_label="/",last_period="5m0s"} 68.61658026228977
disk_used_inodes_percent{gpud_component="disk",gpud_metric_label="/"} 9.353885135135135
```
> /v1/metrics RESPONSE BODY: …
> feat(metrics, server): implement scraper, store, syncer for Prometheus metrics using sqlite as an experimental feature

- pkg/metrics/syncer/syncer_test.go
> test(metrics/syncer): wait longer for syncer start/stop ut for slow CI

- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
- components/accelerator/nvidia/sxid/component.go
- components/accelerator/nvidia/sxid/component_test.go
- components/accelerator/nvidia/sxid/helper.go
- components/accelerator/nvidia/sxid/helper_test.go
- components/accelerator/nvidia/sxid/matcher.go
- components/accelerator/nvidia/xid/component.go
- components/accelerator/nvidia/xid/component_test.go
- components/accelerator/nvidia/xid/helper.go
- components/accelerator/nvidia/xid/helper_test.go
- components/accelerator/nvidia/xid/matcher.go
- pkg/kmsg/events.go
- pkg/kmsg/kmsg.go
1. Fix kmsg package incorrectly calculate boot time.
2. Use kmsg instead of dmesg in xid and sxid components.
3. Improve logs
for #512
> feat(xid,sxid): use kmsg instead of dmesg

- pkg/metrics/syncer/syncer_test.go
```
{"level":"info","ts":"2025-04-01T15:31:45Z","caller":"syncer/syncer.go:70","msg":"purged metrics","purged":0}
syncer_test.go:279:
Error Trace:	/home/runner/work/gpud/gpud/pkg/metrics/syncer/syncer_test.go:279
Error:      	Not equal:
expected: 59
actual  : 60
Test:       	TestStartStop/StartStop
Messages:   	Scrape count should not increase after stopping
--- FAIL: TestStartStop (3.20s)
--- FAIL: TestStartStop/StartStop (3.20s)
```
> test(metrics/syncer): make start/stop tests less flaky for slow CI

- pkg/metrics/syncer/syncer_test.go
Test coverage is still 100%
```
=== RUN   TestStartStop/StartStop
{"level":"info","ts":"2025-04-07T08:54:44Z","caller":"syncer/syncer.go:58","msg":"start purging metrics"}
{"level":"info","ts":"2025-04-07T08:54:44Z","caller":"syncer/syncer.go:41","msg":"start scrap and sync metrics"}
{"level":"info","ts":"2025-04-07T08:54:45Z","caller":"syncer/syncer.go:70","msg":"purged metrics","purged":0}
{"level":"info","ts":"2025-04-07T08:54:46Z","caller":"syncer/syncer.go:70","msg":"purged metrics","purged":0}
{"level":"info","ts":"2025-04-07T08:54:47Z","caller":"syncer/syncer.go:85","msg":"stopping syncer"}
{"level":"info","ts":"2025-04-07T08:54:47Z","caller":"syncer/syncer.go:70","msg":"purged metrics","purged":0}
syncer_test.go:280: 
Error Trace: …
```
> tests(metrics/syncer): remove flaky tests

- pkg/login/gossip.go
- pkg/login/gossip_test.go
- pkg/server/server.go
to clarify that this sends gossip to the control plane.
> feat(login): rename Gossip to SendGossip

- pkg/host/reboot.go
- pkg/session/serve.go
To inform the control plane that the reboot request has been processed, reboot after 10 seconds.
> feat(reboot): reboot after 10s by default

- go.mod
- go.sum
ref. https://nvd.nist.gov/vuln/detail/CVE-2025-29087
c.f., https://github.com/mattn/go-sqlite3/pull/1335 and https://github.com/mattn/go-sqlite3/releases/tag/v1.14.28
> go.mod: upgrade sqlite3 to 1.14.28 for CVE-2025-29087

- components/containerd/pod/component.go
- components/containerd/pod/component_test.go
- pkg/containerd/cri.go
- pkg/containerd/cri_test.go
- pkg/machine-info/machine_info.go
Fix the following /states response:
```json
"component": "containerd-pod",
"states": [
{
"component": "containerd-pod",
"name": "containerd-pod",
"health": "Unhealthy",
"reason": "containerd didn't enable CRI",
"error": "rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService",
"extra_info": {
"data": "{\"containerd_service_active\":true}",
"encoding": "json"
}
}
]
```
> feat(containerd): do not set unhealthy if containerd CRI is not enabled, "containerd --version" as fallback in machine info

- components/disk/component.go
- components/disk/component_test.go
```
{"level":"info","ts":"2025-04-24T09:58:59Z","caller":"disk/component.go:117","msg":"checking disk"}
{"level":"warn","ts":"2025-04-24T09:58:59Z","caller":"disk/component.go:198","msg":"no usage found for mount point","mount_point":"/var/lib/kubelet/pods/0b737df7-7b71-476d-8e6c-01716fa7be1d/volume-subpaths/metrics-config/nvidia-dcgm-exporter/1"}
{"level":"warn","ts":"2025-04-24T09:58:59Z","caller":"disk/component.go:198","msg":"no usage found for mount point","mount_point":"/var/lib/kubelet/pods/865df29e-1193-4e3a-b83d-1278e3714b00/volume-subpaths/nvidia-device-plugin-entrypoint/nvidia-device-plugin/0"}
{"level":"warn","ts":"2025-04-24T09:58:59Z","caller":"disk/component.go:198","msg":"no usage found for mount point","mount_point":"/var/lib/kubelet/pods/670c27b5-4efa-4b84-a5ce-68ba2d9dd7 …
```
> fix(disk): panic on gpud scan

- components/accelerator/nvidia/infiniband/component.go
- components/accelerator/nvidia/infiniband/component_test.go
- pkg/nvidia-query/infiniband/default.go
- pkg/process/process_additional_test.go
> fix(nvidia/infiniband): skip ibstat output checks if thresholds are not set

- cmd/gpud/command/command.go
- cmd/gpud/command/compact.go
> {"level":"info","ts":"2025-04-27T02:22:47Z","caller":"command/compact.go:34","msg":"successfully checked gpud is not running"}
{"level":"info","ts":"2025-04-27T02:22:47Z","caller":"command/compact.go:60","msg":"state file size before compact","size":"36 MB"}
{"level":"info","ts":"2025-04-27T02:22:47Z","caller":"sqlite/sqlite.go:83","msg":"compacting state database"}
{"level":"info","ts":"2025-04-27T02:22:47Z","caller":"sqlite/sqlite.go:88","msg":"successfully compacted state database"}
{"level":"info","ts":"2025-04-27T02:22:47Z","caller":"command/compact.go:70","msg":"state file size after compact","size":"33 MB"}
> feat(gpud): add "gpud compact" command to VACUUM sqlite database (manual)

- e2e/e2e_test.go
- pkg/custom-plugins/component.go
- pkg/custom-plugins/component_test.go
- pkg/custom-plugins/spec_test.go
- pkg/custom-plugins/testdata/plugins.base64.yaml
- pkg/custom-plugins/testdata/plugins.manual.yaml
- pkg/custom-plugins/testdata/plugins.plaintext.0.yaml
- pkg/custom-plugins/testdata/plugins.plaintext.1.yaml
- pkg/custom-plugins/testdata/plugins.plaintext.2.regex.yaml
- pkg/custom-plugins/types.go
- pkg/process/runner_exclusive.go
(to be more distinct from "type" field)
> fix(custom-plugins): fix non-zero exit code commands output parsing, rename "mode" to "run_mode", add e2e tests for manual mode plugin

- cmd/gpud/command/command.go
- cmd/gpud/command/run.go
- cmd/gpud/command/scan.go
- components/accelerator/nvidia/infiniband/component.go
- components/accelerator/nvidia/infiniband/component_test.go
- components/accelerator/nvidia/infiniband/testdata/ibstat.39.0.a100.failed.ibpanic.exit-255.0
- pkg/config/common/config.go
- pkg/config/default.go
- pkg/config/options.go
- pkg/nvidia-query/infiniband/check_thresholds.go
- pkg/nvidia-query/infiniband/check_thresholds_test.go
- pkg/nvidia-query/infiniband/default_test.go
- pkg/nvidia-query/infiniband/ibstat.go
- pkg/nvidia-query/infiniband/ibstat_test.go
- pkg/nvidia-query/infiniband/ibstatus.go
- pkg/nvidia-query/infiniband/ibstatus_test.go
- pkg/nvidia-query/infiniband/testdata/ibstat.39.0.a100.failed.ibpanic.exit-255.0
- pkg/nvidia-query/infiniband/testdata/ibstatus.39.0.a100.all.active.0
- pkg/process/process.go
- pkg/process/process_test.go
- pkg/scan/options.go
- pkg/scan/scan.go
Example:
```
...
CA 'mlx5_7'
CA type: ...
Number of ports: 1
Firmware version: ...
Hardware version: 0
Node GUID: ...
System image GUID: ...
Port 1:
State: Active
Physical state: LinkUp
Rate: 200
Base lid: 13305
LMC: 0
SM lid: 1
Capability mask: ...
Port GUID: ...
Link layer: InfiniBand
ibpanic: [1323906] main: stat of IB device 'mlx5_8' failed: No such file or directory
```
> feat(nvidia/infiniband): use "ibstat" partial output, "ibstatus" fallback (if needed)

- pkg/disk/lsblk_flatten.go
- pkg/disk/lsblk_flatten_test.go
- pkg/disk/testdata/lsblk.4.json
e.g.,
```
+-----------------------+-------+--------+--------+-------------+-----------+-----------------------+
|         NAME          | TYPE  | FSTYPE |  SIZE  | MOUNT POINT |  PARENTS  |       CHILDREN        |
+-----------------------+-------+--------+--------+-------------+-----------+-----------------------+
| loop1                 | loop  |        | 64 MB  |             |           |                       |
| loop10                | loop  |        | 1.0 MB |             |           |                       |
| loop11                | loop  |        | 5.8 MB |             |           |                       |
| loop12                | loop  |        | 16 MB  |             |           |                       |
| loop13                | loop  |        | 18 MB  |             | …
```
> feat(pkg/disk): track up to 2-level depth lsblk children

- pkg/machine-info/machine_info.go
- pkg/nvidia-query/detect.go
- pkg/nvidia-query/detect_test.go
- pkg/nvidia-query/testdata/lspci.gb200
> feat(machine-info): GPU count fallback to pci device list if nvml/nvidia driver has not been loaded

- pkg/server/server.go
- pkg/session/session.go
Split from https://github.com/leptonai/gpud/pull/819.
> {"level":"info","ts":"2025-05-16T10:10:04Z","msg":"session keep alive: checking server health"}
{"level":"info","ts":"2025-05-16T10:10:04Z","msg":"/healthz","status":200,"method":"GET","path":"/healthz","query":"","ip":"127.0.0.1","user-agent":"Go-http-client/1.1","latency":0.000024397,"time":"2025-05-16T10:10:04Z"}
[GIN] 2025/05/16 - 10:10:04 | 200 |      64.628µs |       127.0.0.1 | GET      "/healthz"
> fix(session): health check with correct endpoint

- .goreleaser_linux_arm64_amzn2.yaml
- .goreleaser_linux_arm64_amzn2023.yaml
> fix(goreleaser): use correct compiler triplet for Amazon Linux 2023

- api/v1/types.go
- e2e/e2e_test.go
- pkg/custom-plugins/component.go
- pkg/custom-plugins/component_health_test.go
- pkg/custom-plugins/component_test.go
- pkg/metrics/utils.go
- pkg/metrics/utils_test.go
- pkg/server/handlers_components.go
```
init_plugin_health_state_degraded{gpud_component="init-plugin"} 0
init_plugin_health_state_healthy{gpud_component="init-plugin"} 1
init_plugin_health_state_unhealthy{gpud_component="init-plugin"} 0
...
y9w0v16wbm_health_state_degraded{gpud_component="y9w0v16wbm"} 0
y9w0v16wbm_health_state_healthy{gpud_component="y9w0v16wbm"} 1
y9w0v16wbm_health_state_unhealthy{gpud_component="y9w0v16wbm"} 0
```
> feat(custom-plugins): register health state metrics for custom plugins

- pkg/process/runner_exclusive.go
- pkg/session/serve.go
- pkg/session/session.go
No need to see these logs
```
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"process exited","pid":3855,"exitCode":0}
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"closed running script","pid":3855}
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"process exited","pid":3948,"exitCode":0}
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"process exited","pid":3846,"exitCode":0}
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"closed running script","pid":3846}
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"process exited","pid":3873,"exitCode":0}
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"closed running script","pid":3873}
{"level":"info","ts":"2025-05-22T14:57:50Z","msg":"closed running script","pid":3948} …
```
> feat(pkg/session, process): reduce log noise for non-critical logs

- pkg/custom-plugins/component.go
- pkg/custom-plugins/component_test.go
Do not use the component name again
> health_checks.sw_drv_config_nvidia_smi/health_checks.sw_drv_config_nvidia_smi
should be
> health_checks.sw_drv_config_nvidia_smi/check
> feat(custom-plugins): simplify health state output name as "check"

- pkg/gpud-manager/systemd/gpud.service
Make this similar to containerd.service
And in many OS,
```
sudo systemctl status NetworkManager.service
Unit NetworkManager.service could not be found.
```
> fix(gpud.service): simplify systemd dependency

- cmd/gpud/login/command.go
- cmd/gpud/up/command.go
```
✔ successfully logged in with machine id ...
✔ successfully logged in
```
should be
```
✔ successfully logged in with machine id ...
```
> nit(gpud up): remove redundant login logs

- pkg/machine-info/machine_info.go
> fix(machine-info): skip infiniband link for private ip listing

- pkg/nfs-checker/group_config.go
- pkg/nfs-checker/group_config_test.go
- pkg/nfs-checker/member_config.go
- pkg/nfs-checker/member_config_test.go
> {"level":"info","ts":"2025-06-12T07:52:57Z","msg":"processing update config request","component":"nfs","config":"[{\"dir\":\"/tmp/.gpud-nfs-checker\",\"file_contents\":\"e16e592281e5a5a5d343c2a46626aba4268be48f709e42537bbbbbe3e10d547e\",\"ttl_to_delete\":\"10m0s\",\"num_expected_files\":1}]"}
{"level":"info","ts":"2025-06-12T07:52:57Z","msg":"setting default nfs checker configs","count":1}
> fix(nfs-checker): validate and mkdir target directory if not exists

- components/accelerator/nvidia/nccl/component.go
- components/accelerator/nvidia/nccl/component_test.go
- components/accelerator/nvidia/peermem/component.go
> fix(nvidia/nccl, peermem): add missing cancel calls

- pkg/nvidia-query/nvml/processes.go
- pkg/nvidia-query/nvml/processes_test.go
> fix(nvml/processes): handle "no such file or directory" error when listing gpu processes

- components/accelerator/nvidia/sxid/component.go
- components/accelerator/nvidia/xid/component.go
- pkg/eventstore/database.go
- pkg/server/server.go
> feat(server): retain only 24 hours of metrics/events data (retain xid/sxid/reboot as exceptions)

- pkg/nvidia-query/xid/xid_test.go
We start diverge from the doc, with xid 110, thus remove
> fix(nvidia/xid): remove stale test case

- components/containerd/component.go
> {"level":"error","ts":"2025-07-09T17:34:54.964Z","msg":"error listing pods from kubelet: Get \"http://localhost:10255/pods\": context canceled"}
> fix(containerd): recreate context for kubelet list calls

- components/accelerator/nvidia/infiniband/component.go
- components/accelerator/nvidia/infiniband/component_read_class_test.go
- components/accelerator/nvidia/infiniband/component_test.go
e.g., if out of 12 ports, only 4 are down, and threshold is 8,
then we should not process ib port flap/drop events
> fix(infiniband): skip ib port flap/drop event processing if thresholds are met

- components/cpu/kmsg_matcher.go
- components/cpu/kmsg_matcher_test.go
Before:
> CPU task blocked for more than 120 seconds
After:
> CPU task blocked for more than 120 seconds (jfsmount:136986)
> [LEP-1155] feat(cpu): improve blocked/lockup event readability

- cmd/gpud/command/command.go
- cmd/gpud/update/command.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/server/server_test.go
- pkg/session/serve.go
- pkg/update/update.go
- pkg/update/update_test.go
This fixes the issue where the control plane only
gets the error message "session closed" when it
triggers the GPUd updates.
> [LEP-1172] feat(update): use auto-update-exit-code for systemd managed gpud updates

- components/disk/component.go
- pkg/disk/disk_partition_usage.go
- pkg/disk/metrics.go
```
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.001"} 2
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.005"} 2
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.01"} 2
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.025"} 2
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.05"} 2
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.1"} 2
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.25"} 2
gpud_disk_get_usage_seconds_bucket{gpud_component="disk",mount_point="/projects/data",le="0.5"} 2 …
```
> [LEP-1219] feat(pkg/disk): metrics for getting disk usage (for NFS), re-enable disk usage tracking for nfs partitions

- components/accelerator/nvidia/gpu-counts/component.go
- components/accelerator/nvidia/gpu-counts/component_test.go
Only use them internally within this package,
to evaluate the suggested actions.
> [LEP-1270] [LEP-1325] feat(gpu-counts): do not return events externally

- components/accelerator/nvidia/hw-slowdown/component.go
- components/accelerator/nvidia/hw-slowdown/component_test.go
since we have health states, we don't need to return any events externally.
> [LEP-1325] feat(nvidia/hw-slowdown): simplify hw-slowdown events

- pkg/asn/asn.go
- pkg/machine-info/login_request.go
- pkg/machine-info/machine_info.go
> [LEP-1564] feat(machine-info): log ASN lookup failures, raw ASN name for provider, retries in case of empty ASN name, add OCI as provider

- CONTRIBUTING.md
- Dockerfile
- README.md
- deployments/helm/gpud/templates/daemonset.yaml
- deployments/helm/gpud/values.yaml
**Dockerfile:**
- use CUDA runtime image as Docker base to include the necessary CUDA libraries to interact with the GPU driver
- expose additional build arguments with defaults (OS_NAME=ubuntu, OS_VERSION=22.04, CUDA_VERSION=12.4.1) 
- install missing runtime dependencies (dmidecode, util-linux, kmod, docker, containerd)
- update documentation
**Helm:**
- mark the GPUd pod as a critical add-on to prevent eviction
- set a privileged security context by default
- mount necessary volumes
- add an optional runtimeClassName for better integration with GPU nodes
> Fix container deployment

- components/os/component.go
- components/os/pstore_test.go
> fix(os): do not create pstore store if directory does not exist

- components/disk/component.go
- pkg/server/server.go
> [LEP-1874] [LEP-2000] feat(components, disk): retain/lookback events 2 weeks

- cmd/gpud/command/command.go
- cmd/gpud/run/command.go
- cmd/gpud/scan/command.go
- components/accelerator/nvidia/xid/component.go
- components/accelerator/nvidia/xid/health_state.go
- components/accelerator/nvidia/xid/health_state_test.go
- components/accelerator/nvidia/xid/threshold.go
- components/accelerator/nvidia/xid/threshold_test.go
- pkg/session/serve_update_config.go
- pkg/session/serve_update_config_test.go
- pkg/session/session.go
> feat(nvidia/xid): allow to set reboot threshold (default remains 2)

- components/accelerator/nvidia/memory/component.go
- components/accelerator/nvidia/memory/component_test.go
- pkg/nvidia-query/nvml/error.go
- pkg/nvidia-query/nvml/memory.go
- pkg/nvidia-query/nvml/memory_test.go
Fix
```
{"level":"info","ts":"2025-09-24T12:26:21.523Z","caller":"memory/component.go:105","msg":"checking nvidia gpu memory"}
{"level":"warn","ts":"2025-09-24T12:26:21.523Z","caller":"nvml/memory.go:59","msg":"failed to get device memory info v2, falling back to v1","error":"Not Supported"}
{"level":"warn","ts":"2025-09-24T12:26:21.523Z","caller":"nvml/memory.go:68","msg":"failed to get device memory info v1","error":"Not Supported"}
{"level":"warn","ts":"2025-09-24T12:26:21.523Z","caller":"nvml/memory.go:71","msg":"device memory info v1 is not supported","error":"Not Supported"}
{"level":"info","ts":"2025-09-24T12:26:21.523Z","caller":"memory/component.go:149","msg":"memory","uuid":"GPU-2dee1e25-b3b5-007e-2b55-79f2d0f2ebe5","total":0,"reserved":0,"used":0,"free":0,"used_percent":""} …
```
> fix(nvidia/memory): handle getMemory "Not Supported" error gracefully

- cmd/gpud/notify/command.go
- pkg/login/client.go
- pkg/session/session.go
- pkg/session/session_keepalive.go
1. If the control plane is gpud-gateway, there is no need to call the healthz endpoint, as gpud-gateway supports a cookie-less sticky session mechanism.
2. Add bearer token when sending login request
> chore: support gpud-gateway
