.github/workflows/goreleaser.yml, .goreleaser_linux_amd64_ubuntu24.04.yaml
Address https://github.com/leptonai/gpud/issues/31.
=> feat(goreleaser): support linux/amd64 ubuntu 24.04 builds

components/query/log/tail/scan.go
Address https://github.com/leptonai/gpud/issues/32.
=> fix(query/log/tail): do not show output on scan failures

install.sh
Address https://github.com/leptonai/gpud/issues/31.
Need https://github.com/leptonai/gpud/pull/34.
=> feat(install.sh): detect ubuntu distro version

components/dmesg/config.go
Address https://github.com/leptonai/gpud/issues/32.
=> fix(dmesg): fallback in case "dmesg --since" flag doesn't exist in older versions

components/accelerator/nvidia/query/nvml/gpm.go, components/accelerator/nvidia/query/nvml/nvml.go, components/accelerator/nvidia/query/nvml/xid.go, components/accelerator/nvidia/query/xid/xid.go
c.f., https://github.com/NVIDIA/k8s-device-plugin/issues/945
=> fix(nvidia/nvml): mark xid 68 as user app error, document

components/accelerator/nvidia/query/nvidia_peermem.go, components/diagnose/diagnose.go, components/query/log/tail/scan.go, pkg/process/process.go, pkg/process/process_test.go, pkg/systemd/journal.go, pkg/systemd/journal_test.go
Will be useful for fabric manager service debugging.
=> feat(pkg/process): rename stop to abort, add systemd/journal utils

components/accelerator/nvidia/peermem/component.go, components/accelerator/nvidia/query/peermem/dmesg.go, components/accelerator/nvidia/query/peermem/dmesg_test.go, components/dmesg/filters_nvidia.go, components/query/log/poller.go
If repeated, it indicates the GPU performance issues
=> feat(nvidia/peermem): track dmesg events for invalid context errors

components/accelerator/nvidia/clock-speed/component_output.go, components/accelerator/nvidia/clock/component_output.go, components/accelerator/nvidia/ecc/component_output.go, components/accelerator/nvidia/error/component_output.go, components/accelerator/nvidia/fabric-manager/component_output.go, components/accelerator/nvidia/infiniband/component_output.go, components/accelerator/nvidia/info/component_output.go, components/accelerator/nvidia/memory/component_output.go, components/accelerator/nvidia/nvlink/component_output.go, components/accelerator/nvidia/peermem/component_output.go, components/accelerator/nvidia/power/component_output.go, components/accelerator/nvidia/processes/component_output.go, components/accelerator/nvidia/temperature/component_output.go, components/accelerator/nvidia/utilization/component_output.go
Cherry-picking from https://github.com/leptonai/gpud/pull/82.
=> fix(nvidia): return empty output object if smi/nvml is nil

components/accelerator/nvidia/query/sxid/sxid.go
ref. https://docs.nvidia.com/datacenter/tesla/pdf/fabric-manager-user-guide.pdf
c.f., https://github.com/leptonai/gpud/pull/81
=> feat(nvidia): add non-fatal sxid "20012" code, rename Detail.ID to SXID

components/fd/component_output.go, components/fd/get_limit_darwin.go, components/fd/get_limit_linux.go, components/fd/get_limit_test.go, components/fd/get_limit_windows.go
=> fix(components/fd): rename "fd_max_file_exists" to "fd_limit_supported", fix get limit on darwin

.goreleaser_linux_amd64_amzn2.yaml, .goreleaser_linux_amd64_amzn2023.yaml, install.sh
Address https://github.com/leptonai/gpud/issues/90.
=> feat(build, release): support Amazon Linux 2 and 2023 (experimental)

components/accelerator/nvidia/query/query.go, components/systemd/component.go, components/systemd/component_output.go
Address https://github.com/leptonai/gpud/issues/103.
=> fix(systemd, nvidia): mark dbus connection not available if not initialized, to avoid nil pointer panic

install.sh
To help debug the issue https://github.com/leptonai/gpud/issues/102.
=> fix(install.sh): fix install doc links

install.sh
To help debug https://github.com/leptonai/gpud/issues/102.
=> fix(install.sh): print download failure debugging info

components/accelerator/nvidia/fabric-manager/config.go, components/accelerator/nvidia/nccl/component.go, components/accelerator/nvidia/nccl/config.go, components/accelerator/nvidia/nccl/id/id.go, components/accelerator/nvidia/peermem/component.go, components/accelerator/nvidia/peermem/id/id.go, components/accelerator/nvidia/query/fabric-manager-log/log.go, components/accelerator/nvidia/query/fabric-manager-log/log_test.go, components/accelerator/nvidia/query/nccl/dmesg.go, components/accelerator/nvidia/query/nccl/dmesg_test.go, components/accelerator/nvidia/query/peermem/dmesg.go, components/accelerator/nvidia/query/peermem/dmesg_test.go, components/dmesg/filters_nvidia.go, config/default.go, docs/COMPONENTS.md, internal/server/server.go
To start monitoring NCCL issue like:
> [Thu Oct 10 03:06:53 2024] pt_main_thread[2536443]: segfault at 7f797fe00000 ip 00007f7c7ac69996 sp 00007f7c12fd7c30 error 4 in libnccl.so.2[7f7c7ac00000+d3d3000]
=> fix(fabric manager, nccl): fix fabric manager regex, add NCCL monitoring using dmesg

components/accelerator/nvidia/query/nvml/nvml.go, components/accelerator/nvidia/query/query.go, go.mod, go.sum
c.f., https://github.com/NVIDIA/go-nvlib/pull/44
=> feat(nvidia/nvml): update nvlib to 0.7.0, rename device ID fields

components/diagnose/scan.go, components/library/component.go, config/default.go, docs/COMPONENTS.md, internal/server/server.go, pkg/file/library.go, pkg/file/library_darwin.go, pkg/file/library_linux.go, pkg/file/library_test.go, pkg/file/library_windows.go
> ⌛ scanning nvidia accelerators
✔ found library libnvidia-ml.so at /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.535.183.06
✔ found library libcuda.so at /usr/lib/x86_64-linux-gnu/libcuda.so.535.183.06
This is similar to what `NVIDIA/nvidia-container-toolkit` does:
https://github.com/NVIDIA/nvidia-container-toolkit/blob/4604e3b6c86aba52c7fe54241070d493938a28e6/internal/lookup/library.go#L33-L62
Useful when early detecting issues like:
```
Failed to launch photon: <class 'pynvml.NVMLError_LibraryNotFound'>: NVML Shared
Library Not Found...line 2248, in
_LoadNvmlLibrary
nvmlLib = CDLL("libnvidia-ml.so.1")
File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
self._handle = _dlopen(self._name, mode)
OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or …
```
=> feat(components/library): periodically check libnvidia/libcuda* (experimental)

cmd/gpud/command/command.go, cmd/gpud/command/run.go, components/docker/container/component.go, components/docker/container/component_output.go, components/docker/container/config.go, config/default.go, config/op_options.go, internal/server/server.go
c.f., https://github.com/leptonai/gpud/pull/109
Fix
=> fix(docker-container): "gpud run --docker-ignore-connection-errors" to ignorer docker daemon connection errors (do not ignore by default)

components/accelerator/nvidia/persistence-mode/component.go, components/accelerator/nvidia/persistence-mode/component_output.go, components/accelerator/nvidia/persistence-mode/config.go, components/accelerator/nvidia/persistence-mode/id/id.go, components/accelerator/nvidia/query/nvidia_persistenced.go, components/accelerator/nvidia/query/nvidia_smi_query_gpu.go, components/accelerator/nvidia/query/nvml/nvml.go, components/accelerator/nvidia/query/nvml/persistence_mode.go, components/accelerator/nvidia/query/query.go, config/default.go, docs/COMPONENTS.md, internal/server/server.go
> NVML GPU-942f36ee-fd3c-8203-c213-54df7ea7dc8f
>
> ✔ NVML persistence mode is enabled (nvidia-persistenced running true)
=> feat(nvidia): add persistence-mode (both legacy, persistenced daemon checks), implements `DCGM_FR_PERSISTENCE_MODE` in DCGM

cmd/gpud/command/command.go, cmd/gpud/command/run.go, config/config.go, config/config_test.go, internal/server/server.go, internal/session/serve.go, internal/session/session.go, internal/session/session_test.go, update/update.go
Address https://github.com/leptonai/gpud/issues/103.
=> feat(gpud): "gpud run --auto-update-exit-code" for daemon set auto update use case (optional)

components/accelerator/nvidia/query/nvidia_smi_query.go, components/accelerator/nvidia/query/nvidia_smi_query_test.go, components/accelerator/nvidia/query/testdata/nvidia-smi-query.560.35.03.out.0.valid
Fix the nvidia-smi parsing error
=> fix(nvidia-smi/parse): do not parse remapped rows N/A

components/accelerator/nvidia/bad-envs/component.go, components/accelerator/nvidia/clock-speed/component.go, components/accelerator/nvidia/clock/component.go, components/accelerator/nvidia/ecc/component.go, components/accelerator/nvidia/error/component.go, components/accelerator/nvidia/fabric-manager/component.go, components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/info/component.go, components/accelerator/nvidia/memory/component.go, components/accelerator/nvidia/nvlink/component.go, components/accelerator/nvidia/peermem/component.go, components/accelerator/nvidia/persistence-mode/component.go, components/accelerator/nvidia/power/component.go, components/accelerator/nvidia/processes/component.go, components/accelerator/nvidia/remapped-rows/component.go, components/accelerator/nvidia/temperature/component.go, components/accelerator/nvidia/utilization/component.go, components/containerd/pod/component.go, components/cpu/component.go, components/disk/component.go, components/docker/container/component.go, components/fd/component.go, components/k8s/pod/component.go, components/memory/component.go, components/os/component.go, components/power-supply/component.go, components/query/poller.go, components/query/poller_test.go, components/systemd/component.go, components/tailscale/component.go
=> fix(components): do not panic when there's no data collected yet

components/accelerator/nvidia/gpm/component.go, components/accelerator/nvidia/query/metrics/gpm/metrics.go, components/accelerator/nvidia/query/nvml/gpm.go, components/accelerator/nvidia/query/nvml/nvml.go, components/accelerator/nvidia/query/nvml/options.go
Signed-off-by: Zhiting Zhu <zhitingz@lepton.ai>
=> feat(nvidia): exposing SM core and tensor core metrics in GPUd

README.md, charts/gpud/.helmignore, charts/gpud/Chart.yaml, charts/gpud/README.md, charts/gpud/templates/daemonset.yaml, charts/gpud/values.yaml
Address https://github.com/leptonai/gpud/issues/103.
=> feat(charts): add gpud run helm chart

components/accelerator/nvidia/error/xid/component.go, components/accelerator/nvidia/gpm/component.go
Fix
> {"level":"error","ts":"2024-10-26T11:43:35Z","caller":"log/log.go:60","msg":"failed to invoke component state","operation":"GetStates","component":"accelerator-nvidia-error-xid","error":"no data collected yet in the poller","stacktrace":"github.com/leptonai/gpud/log.(*LeptonLogger).Errorw\n\t/root/leptonai/gpud/log/log.go:60\ngithub.com/leptonai/gpud/internal/session.(*Session).getStates\n\t/root/leptonai/gpud/internal/session/serve.go:250\ngithub.com/leptonai/gpud/internal/session.(*Session).serve\n\t/root/leptonai/gpud/internal/session/serve.go:67"}
=> fix(nvidia/xid): do not error log when no xid happened yet

components/accelerator/nvidia/infiniband/component_output.go, components/accelerator/nvidia/infiniband/component_output_test.go, components/accelerator/nvidia/query/query.go
=> fix(nvidia/infiniband): do not set unhealthy if infiniband is not supported

go.mod, go.sum
https://github.com/mattn/go-sqlite3/commit/82bc911e85b3def2940e41767480745bcbb6ef45
=> feat(go.mod): bump up mattn/go-sqlite3 to @82bc911

cmd/gpud/command/login.go, cmd/gpud/command/utils.go, components/metrics/averager_test.go, components/metrics/state/state_test.go, components/query/log/state/state_test.go, components/query/poller.go, components/state/api_version_test.go, components/state/state.go, components/state/state_test.go, internal/server/server.go, pkg/sqlite/sqlite.go
=> feat(pkg/sqlite): add Open function, remove unused table name

components/accelerator/nvidia/query/nvml/nvml.go, components/accelerator/nvidia/query/query.go
=> nit(components/nvidia/query): pass options to start default instance

components/accelerator/nvidia/fabric-manager/component.go, components/dmesg/component.go, components/query/log/poller.go, components/query/log/poller_test.go, components/query/poller.go
=> feat(component/events): return query.ErrNoData if no event is found

components/query/log/tail_scan.go
```json
{
"component": "accelerator-nvidia-error-xid",
"startTime": "2024-11-15T04:48:56Z",
"endTime": "2024-11-20T04:58:08.477072772Z",
"events": [
{
"time": "2024-11-20T04:10:23Z",
"name": "error_xid",
"message": "xid 119 detected by dmesg (47 minutes ago)",
"extra_info": {
"data": "{\"time\":\"2024-11-20T04:10:23Z\",\"data_source\":\"dmesg\",\"device_uuid\":\"\",\"xid\":119,\"suggested_actions_by_gpud\":{\"references\":[\"\\\"Xid 119, 120: GSP RPC Timeout / GSP Error\\\", https//docs.nvidia.com/deploy/xid-errors/index.html#xid-119-120-gsp-rpc-timeout-gsp-error (accessed on Nov 3, 2024)\",\"\\\"NVIDIA Xid Errors\\\", https://docs.nvidia.com/deploy/xid-errors/index.html (accessed on Nov 3, 2024)\",\"\\\"NVIDIA Xid Errors\\\", https://docs.nvidia.com/deploy/pdf/XID_Errors.pdf (Sep …
```
=> fix(log/tail): correctly collect xid/sxid events from log scanner

components/diagnose/scan.go, components/os/component_output.go, pkg/host/host.go
> ⌛ scanning the host
>
> ✔ detected virtualization environment "lxc"
> ✔ detected system manufacturer "Dell Inc."
=> feat(components/os): detect virt environment, system manufacturer

components/accelerator/detect.go, components/accelerator/nvidia/query/detect.go, components/accelerator/nvidia/query/infiniband/infiniband.go, components/accelerator/nvidia/query/nvidia_persistenced.go, components/accelerator/nvidia/query/nvidia_smi_query.go, components/accelerator/nvidia/query/peermem/peermem.go, components/disk/component_output.go, config/default.go, manager/controllers/package_controller.go, pkg/disk/disk.go, pkg/disk/lsblk.go, pkg/host/machine_id.go, pkg/host/virt.go, pkg/pci/pci.go, pkg/process/examples/simple-command/main.go, pkg/process/examples/simple-commands/main.go, pkg/process/examples/stream-blocking-commands/main.go, pkg/process/examples/stream-commands/main.go, pkg/process/process_test.go, pkg/process/utils.go, pkg/process/utils_test.go, pkg/reboot/reboot.go, pkg/systemd/journal.go, pkg/systemd/systemd.go
Also fix
> {"level":"error","ts":"2024-12-13T13:20:29Z","caller":"controllers/package_controller.go:323","msg":"failed to read stout: read |0: file already closed","stacktrace":"[github.com/leptonai/gpud/manager/controllers.runCommand.func1](http://github.com/leptonai/gpud/manager/controllers.runCommand.func1)\n\t/root/leptonai/gpud/manager/controllers/package_controller.go:323"}
=> feat(process): read stderr in case of command failures, improve disk get error handling

manager/controllers/package_controller.go
c.f., https://github.com/leptonai/gpud/pull/252
=> fix(controller): only read stdout for run command

pkg/process/process.go, pkg/process/process_test.go, pkg/process/utils.go, pkg/process/utils_test.go
=> fix(pkg/process): gracefully handle read operations on aborted process, Read to return error if not started

.github/workflows/build.yml
Fix CI failures in https://github.com/leptonai/gpud/pull/291
=> fix(ci): bump up linux header deps

components/accelerator/nvidia/query/xid-sxid-state/cache.go, components/accelerator/nvidia/query/xid-sxid-state/cache_test.go, components/accelerator/nvidia/query/xid-sxid-state/state.go, go.mod, go.sum, internal/server/server.go
Similar to https://github.com/leptonai/gpud/pull/301
=> feat(nvidia/sxid-xid-state): dedup in memory by minute level to minimize contending db inserts

.github/workflows/goreleaser.yml, .goreleaser_linux_arm64_amzn2.yaml, .goreleaser_linux_arm64_amzn2023.yaml, .goreleaser_linux_arm64_ubuntu20.04.yaml, .goreleaser_linux_arm64_ubuntu22.04.yaml, .goreleaser_linux_arm64_ubuntu24.04.yaml
Signed-off-by: Zhiting Zhu <zhitingz@lepton.ai>
=> chore(build): support arm64 build for linux

pkg/dmesg/testdata/dmesg.decode.iso.log.0, pkg/dmesg/testdata/dmesg.decode.iso.log.1, pkg/dmesg/watcher.go, pkg/dmesg/watcher_test.go
Addressing all feedback from https://github.com/leptonai/gpud/pull/315.
=> feat(pkg/dmesg): simpler watcher

internal/session/serve.go
c.f., https://github.com/leptonai/gpud/pull/321
=> feat(internal/session): set ib ports/rates dynamically

components/accelerator/nvidia/query/sxid/dmesg/dmesg.go, components/accelerator/nvidia/query/sxid/dmesg/dmesg_test.go, components/accelerator/nvidia/query/xid/dmesg/dmesg.go, components/accelerator/nvidia/query/xid/dmesg/dmesg_test.go
For https://github.com/leptonai/gpud/pull/321.
=> feat(nvidia/xid,sxid/dmesg): add dmesg log line matcher, xid/sxid extractor

client/v1/healthz_test.go, components/accelerator/nvidia/query/nvidia_smi_query.go, components/accelerator/nvidia/query/nvidia_smi_query_test.go
To fix the current PR test failures for coverage (e.g., https://github.com/leptonai/gpud/pull/339), due to indirect changes.
=> test(client/v1, nviai/query): increase unit test coverage

pkg/sqlite/metrics_test.go, pkg/sqlite/options_test.go, pkg/sqlite/sqlite_test.go, pkg/sqlite/test_utils_test.go
```
coverage: 87.7% of statements
ok      github.com/leptonai/gpud/pkg/sqlite     0.402s
```
=> test(pkg/sqlite): increase test coverage

components/state/api_version.go, components/state/api_version_test.go, components/state/state_test.go
=> fix(components/state): clean up update queries, increase unit test coverage, read last API version using SQLite rowid column

.github/workflows/goreleaser.yml, go.mod, go.sum
ref. https://github.com/leptonai/gpud/issues/365
=> releaser(ci, go): use go 1.23.6, disable arm releaser for now

.github/workflows/goreleaser-dev.yml, .goreleaser_darwin_amd64.yaml, .goreleaser_darwin_arm64.yaml, .goreleaser_linux_amd64.yaml, .goreleaser_linux_amd64_amzn2.yaml, .goreleaser_linux_amd64_amzn2023.yaml, .goreleaser_linux_amd64_ubuntu20.04.yaml, .goreleaser_linux_amd64_ubuntu22.04.yaml, .goreleaser_linux_amd64_ubuntu24.04.yaml, .goreleaser_linux_arm64_amzn2.yaml, .goreleaser_linux_arm64_amzn2023.yaml, .goreleaser_linux_arm64_ubuntu20.04.yaml, .goreleaser_linux_arm64_ubuntu22.04.yaml, .goreleaser_linux_arm64_ubuntu24.04.yaml
Signed-off-by: Zhiting Zhu <zhitingz@lepton.ai>
=> fix(build): fix arm64 build

manager/packages/packages_test.go
=> test(manager/packages): add unit test cases

pkg/systemd/dbus.go, pkg/systemd/dbus_test.go
=> test(pkg/systemd): add more unit tests to increasing coverage

pkg/process/process.go, pkg/process/process_test.go, pkg/process/utils_test.go
For https://github.com/leptonai/gpud/pull/371.
=> feat(process): support "ExitCode" method

components/accelerator/nvidia/query/infiniband/ibstat.go, components/accelerator/nvidia/query/infiniband/ibstat_test.go
For https://github.com/leptonai/gpud/pull/371.
=> fix(infiniband): surface ibstat parse failures, remove "down" match fallback for healthiness

components/accelerator/nvidia/query/infiniband/ibstat.go, components/accelerator/nvidia/query/infiniband/ibstat_test.go, config/options.go
=> fix(infiniband): return explicit errors for command not found

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go
=> fix(infiniband): unit tests with specified ib threshold (do not use global threshold)

components/accelerator/nvidia/query/query.go
=> feat(nvidia): remove ibstat call from shared poller

components/accelerator/nvidia/query/nvml/clock_events_test.go, components/accelerator/nvidia/query/nvml/clock_speed.go, components/accelerator/nvidia/query/nvml/clock_speed_test.go, components/accelerator/nvidia/query/nvml/error_test.go, components/accelerator/nvidia/query/nvml/testutil/clock_speed.go, components/accelerator/nvidia/query/nvml/testutil/clock_speed_test.go, components/accelerator/nvidia/query/nvml/testutil/util.go, components/accelerator/nvidia/query/nvml/testutil/util_test.go
Using https://pkg.go.dev/github.com/NVIDIA/go-nvml@v0.12.4-0/pkg/nvml/mock
=> test(nvidia/query/nvml): add clock speed, errors unit tests using mock/nvml

components/accelerator/nvidia/error/sxid/component.go, components/accelerator/nvidia/error/xid/component.go, components/os/component.go, components/os/component_output.go, components/os/component_test.go, pkg/reboot/reboot.go, pkg/reboot/reboot_test.go
=> fix(xid/sxid): rely on last reboot first

components/os/component_output.go, components/os/component_output_test.go
=> fix(os): log which command fails when context timeout in get

components/memory/component.go, components/memory/dmesg_matcher.go, components/memory/dmesg_matcher_test.go, components/memory/watcher.go, pkg/dmesg/deduper_test.go
=> nits(components/memory): set missing message field in events, update "New"

pkg/dmesg/log_line_processor.go, pkg/dmesg/log_line_processor_test.go
=> feat(dmesg): log line processor for dmesg

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go
Fix https://github.com/leptonai/gpud/issues/409.
=> fix(infiniband): set /states unhealthy when thresholds set but ibstat not found

pkg/dmesg/deduper_test.go
```
=== RUN   TestDedupLogLines/should_deduplicate_same_content_across_multiple_seconds
deduper_test.go:294: 
Error Trace:	/home/runner/work/gpud/gpud/pkg/dmesg/deduper_test.go:294
Error:      	Not equal: 
expected: 5
actual  : 0
Test:       	TestDedupLogLines/should_deduplicate_same_content_across_multiple_seconds
Messages:   	expected five log lines (one per second) after deduplication
deduper_test.go:301: 
Error Trace:	/home/runner/work/gpud/gpud/pkg/dmesg/deduper_test.go:301
Error:      	Not equal: 
expected: 5
actual  : 0
Test:       	TestDedupLogLines/should_deduplicate_same_content_across_multiple_seconds
Messages:   	expected five different timestamps
=== RUN   TestDedupLogLines/should_not_deduplicate_same_second_logs_with_slightly_different_content …
```
=> test(pkg/dmesg): make "TestDedupLogLines" deterministic in slow CI

pkg/gpud-state/api_version.go, pkg/gpud-state/api_version_test.go
=> fix(gpud-state): do not rollback if apiversion update committed successfully

pkg/dmesg/deduper_test.go
```
--- PASS: TestDedupLogLines (0.01s)
--- PASS: TestDedupLogLines/should_deduplicate_log_lines_with_same_second_timestamp (0.00s)
--- PASS: TestDedupLogLines/should_not_deduplicate_log_lines_with_different_second_timestamps (0.00s)
--- PASS: TestDedupLogLines/should_deduplicate_mixed_log_lines_with_same_and_different_seconds (0.00s)
--- PASS: TestDedupLogLines/should_deduplicate_same_content_across_multiple_seconds (0.00s)
--- PASS: TestDedupLogLines/should_not_deduplicate_same_second_logs_with_slightly_different_content (0.00s)
--- PASS: TestDedupLogLines/should_deduplicate_log_lines_with_same_content_but_different_trailing_whitespaces (0.00s)
=== RUN   TestWatchPeerMemLogs
{"level":"warn","ts":"2025-02-14T14:16:52Z","caller":"dmesg/watcher.go:148","msg":"skipping duplicate log …
```
=> test(dmesg): make peer mem logs watch tests less flaky

components/systemd/component_output.go, pkg/systemd/systemd.go
=> feat(systemd): do not return error on uptime check failures

pkg/dmesg/deduper_test.go
Fix
```
=== RUN   TestDedupLogLines/should_not_deduplicate_same_second_logs_with_slightly_different_content
deduper_test.go:348: 
Error Trace:	/home/runner/work/gpud/gpud/pkg/dmesg/deduper_test.go:348
Error:      	Not equal: 
expected: 2
actual  : 0
Test:       	TestDedupLogLines/should_not_deduplicate_same_second_logs_with_slightly_different_content
Messages:   	expected two log lines (one for each unique content)
deduper_test.go:361: 
Error Trace:	/home/runner/work/gpud/gpud/pkg/dmesg/deduper_test.go:361
Error:      	Not equal: 
expected: 2
actual  : 0
Test:       	TestDedupLogLines/should_not_deduplicate_same_second_logs_with_slightly_different_content
Messages:   	expected both line numbers (127 and 128) to be present
deduper_test.go:362: 
Error Trace: …
```
=> test(pkg/dmesg): make dedup log line tests more deterministic with waits

pkg/dmesg/log_line_processor.go, pkg/dmesg/log_line_processor_test.go
=> feat(dmesg): set default dmesg watcher in log line processor if not specified

pkg/dmesg/deduper_test.go
=> test(dmesg): output more details for flaky tests

components/accelerator/nvidia/nccl/dmesg_matcher.go, components/accelerator/nvidia/nccl/dmesg_matcher_test.go, components/accelerator/nvidia/peermem/dmesg_matcher.go, components/accelerator/nvidia/peermem/dmesg_matcher_test.go, components/cpu/dmesg_matcher.go, components/cpu/dmesg_matcher_test.go, components/fd/dmesg_matcher.go, components/fd/dmesg_matcher_test.go, components/memory/dmesg_matcher.go, components/memory/dmesg_matcher_test.go, pkg/dmesg/log_line_processor.go, pkg/dmesg/log_line_processor_test.go, pkg/query/log/common/match.go, pkg/query/log/tail/options.go, pkg/query/log/tail/scan_test.go
- **feat(dmesg): match func with regex**
- **tail**
=> feat(dmesg, log): support match func in log scanner

cmd/gpud/command/command.go, cmd/gpud/command/logs.go, cmd/gpud/command/run.go, cmd/gpud/command/scan.go, cmd/gpud/command/up.go, e2e/e2e_test.go, go.mod, go.sum, pkg/gpud-manager/systemd/gpud.logrotate.conf, pkg/gpud-manager/systemd/gpud.service, pkg/gpud-manager/systemd/systemd.go, pkg/log/log.go, pkg/log/log_test.go
Address https://github.com/leptonai/gpud/issues/410
=> cmd(gpud): support "run --log-file" with built-in log rotation

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go, pkg/server/server.go
=> feat(infiniband): use events store to track historical ibstat status

pkg/nvidia-query/nvml/nvml.go, pkg/nvidia-query/query.go, pkg/server/server.go
=> feat(nvidia-query/server): remove redundant channel select, log more

pkg/nvidia-query/nvml/error.go, pkg/nvidia-query/nvml/error_test.go, pkg/nvidia-query/nvml/gpm.go
=> feat(nvidia-query): use "ERROR_ARGUMENT_VERSION_MISMATCH" to decide whether GPM is supported or not

components/accelerator/nvidia/error/xid/dmesg_test.go, components/accelerator/nvidia/error/xid/testdata/dmesg-with-xid-119.log
=> tests(error/xid): add more nvrm dmesg regex unit tests for Xid 119

pkg/dmesg/deduper_test.go, pkg/dmesg/watcher.go
=> test(dmesg): add missing close func call, reduce flakiness in dmesg unit tests

e2e/mock/lspci/lspci_mock_test.go, pkg/nvidia-query/nvml/temperature.go, pkg/nvidia-query/nvml/temperature_test.go, pkg/nvidia-query/nvml/utilization_test.go
=> tests(pkg/nvidia/nvml): unit test for util/temp files, fix flaky mock tests

pkg/process/options_test.go, pkg/process/pids_test.go, pkg/process/process_additional_test.go, pkg/process/read_test.go, pkg/process/utils_test.go
=> tests(pkg/process): increase unit test coverage

pkg/nvidia-query/nvml/clock_events_test.go, pkg/nvidia-query/nvml/clock_speed_test.go
=> tests(nvidia/nvml): increase test coverage of clock events/speed

pkg/nvidia-query/nvml/power_test.go, pkg/nvidia-query/nvml/processes_test.go, pkg/nvidia-query/nvml/remapped_rows.go, pkg/nvidia-query/nvml/remapped_rows_test.go
=> tests(nvidia-query/nvml): more unit tests using nvml mock

pkg/dmesg/watcher.go
Address https://github.com/leptonai/gpud/issues/440.
=> feat(dmesg): log dropped events due to channel full

components/accelerator/nvidia/nccl/component.go, components/accelerator/nvidia/peermem/component.go, components/cpu/component.go, components/fd/component.go, components/memory/component.go, pkg/dmesg/log_line_processor.go, pkg/dmesg/log_line_processor_test.go
=> feat(pkg/dmesg): simplify log line processor create funcs

components/accelerator/nvidia/hw-slowdown/component.go, components/accelerator/nvidia/hw-slowdown/component_test.go
=> feat(nvidia/hw-slowdown): display data_sources in alert message

pkg/log/log_test.go
=> tests(pkg/log): add more unit tests

pkg/nvidia-query/nvidia_smi_query.go, pkg/nvidia-query/nvidia_smi_query_test.go
=> feat(nvidia-query/nvidia-smi): improve attacahed GPUs mismatch error message

cmd/gpud/command/join.go, pkg/login/gossip.go, pkg/login/gossip_test.go, pkg/login/login.go, pkg/login/login_test.go, pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
=> feat(pkg/login): unit testable code base, add unit tests

cmd/gpud/command/join.go, pkg/latency/latency.go, pkg/latency/latency_test.go
=> feat(pkg/latency): "Closest" helper for "join" region detection

cmd/gpud/command/down.go, cmd/gpud/command/up.go, pkg/update/download.go, pkg/update/download_test.go, pkg/update/system.go, pkg/update/update.go, pkg/update/update_test.go
=> feta(pkg/update): split into smaller files, add unit tests

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go, components/accelerator/nvidia/infiniband/dmesg_watcher.go, components/accelerator/nvidia/infiniband/dmesg_watcher_test.go, docs/COMPONENTS.md
Fix https://github.com/leptonai/gpud/issues/348.
=> feat(nvidia/infiniband): watch mellanox power events via dmesg/kernel

pkg/session/serve.go, pkg/session/serve_test.go
otherwise, the server will receive
> "error": {}
=> fix(session/serve): fix response error JSON encoding

pkg/nvidia-query/nvml/nvlink_test.go
=> tests(nvidia-query/nvml): add more unit tests for nvlink calls

pkg/nvidia-query/nvml/ecc_errors_test.go, pkg/nvidia-query/nvml/ecc_mode_test.go, pkg/nvidia-query/nvml/gpm_test.go, pkg/nvidia-query/nvml/gsp_firmware_test.go, pkg/nvidia-query/nvml/memory_test.go, pkg/nvidia-query/nvml/persistence_mode_test.go, pkg/nvidia-query/nvml/processes.go, pkg/nvidia-query/nvml/testutil/gpm.go, pkg/nvidia-query/nvml/testutil/gpm_test.go, pkg/nvidia-query/nvml/testutil/gps_firmware_test.go, pkg/nvidia-query/nvml/testutil/gsp_firmware.go, pkg/nvidia-query/nvml/testutil/memory.go, pkg/nvidia-query/nvml/testutil/memory_test.go, pkg/nvidia-query/nvml/testutil/persistence_mode.go, pkg/nvidia-query/nvml/testutil/persistence_mode_test.go
=> tests(nvidia/nvml): add more unit tests

pkg/session/serve.go
=> nit(session): simplify "delete" handling

components/accelerator/nvidia/ecc/component_output.go, components/accelerator/nvidia/ecc/component_output_test.go, components/accelerator/nvidia/persistence-mode/component_output.go, components/accelerator/nvidia/processes/component.go, pkg/nvidia-query/nvidia_smi_query.go, pkg/nvidia-query/nvidia_smi_query_gpu.go, pkg/nvidia-query/nvidia_smi_query_gpu_test.go, pkg/nvidia-query/nvidia_smi_query_test.go
=> feat(nvidia-query): remove some redundant nvidia-smi dependencies

components/accelerator/nvidia/error/sxid/component.go, components/accelerator/nvidia/error/xid/component.go, components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/nccl/component.go, components/accelerator/nvidia/peermem/component.go, components/cpu/component.go, components/fd/component.go, components/memory/component.go, pkg/kmsg/events.go, pkg/kmsg/kmsg.go
c.f., https://github.com/leptonai/gpud/pull/491
=> feat(components): watch with kmsg (experimental)

pkg/host/boot_id.go, pkg/host/boot_id_test.go, pkg/host/machine_id.go, pkg/host/machine_id_test.go, pkg/host/testdata/machine_id_sample
=> tests(pkg/host): add more uts

components/accelerator/nvidia/remapped-rows/component_output.go, pkg/common/action.go, pkg/nvidia-query/gpu_memory.go
=> nits(nvidia/row-remapping): log row remapping states, document memory capability

go.mod, pkg/gpud-metrics/averager_test.go, pkg/gpud-metrics/metrics_test.go
=> tests(gpud-metrics): add more unit tests

components/accelerator/nvidia/remapped-rows/component_output.go
=> feat(nvidia/remappined-rows): only suggest hw inspection if not reboot

components/cpu/component.go, components/cpu/component_test.go
=> feat(cpu): remoev unused physical cores field

cmd/gpud/command/accelerator.go, cmd/gpud/command/join.go, pkg/accelerator/accelerator.go, pkg/nvidia-query/detect.go, pkg/nvidia-query/nvml/clock_events.go, pkg/nvidia-query/nvml/gpm.go, pkg/nvidia-query/nvml/lib/lib.go, pkg/nvidia-query/nvml/lib/lib_test.go, pkg/nvidia-query/nvml/lib/options.go, pkg/nvidia-query/nvml/nvml.go, pkg/nvidia-query/nvml/nvml_test.go
> {"level":"info","ts":"2025-03-13T06:37:35Z","caller":"nvml/nvml.go:39","msg":"injecting remapped rows pending","corrRows":0,"uncRows":10,"isPending":true,"failureOccurred":false}
> ...
> {"level":"warn","ts":"2025-03-13T06:38:09Z","caller":"remapped-rows/component_output.go:141","msg":"suggested actions","suggestedActions":"REBOOT_SYSTEM"}
=> feat(nvidia): simulate "get remapped rows" (optional)

components/accelerator/nvidia/sxid/helper.go, components/accelerator/nvidia/xid/helper.go
=> fix(xid + sxid): truncate repair actions to pick hw inspection after reboot

components/containerd/pod/component_test.go, components/containerd/pod/cri.go, components/containerd/pod/cri_test.go
=> feat(containerd): reduce/simplify CRI list calls

pkg/kmsg/deduper.go, pkg/kmsg/deduper_test.go, pkg/kmsg/kmsg.go, pkg/kmsg/kmsg_test.go, pkg/kmsg/testdata/kmsg.2.peermem.log
=> feat(kmsg): add default deduper by second-scale

components/components.go, components/info/component.go, components/info/component_output.go, components/info/component_test.go, components/info/id/id.go, e2e/e2e_test.go, pkg/config/default.go, pkg/server/server.go
=> feat(components/info): simplify /states with struct

components/containerd/pod/component.go, components/containerd/pod/component_test.go
=> feat(containerd/pod): improve list pod sandbox error message in /states

components/containerd/pod/cri.go
Help with the wrong connection state transition issue:
```
unexpected fault address 0x63096d3654090
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63096d3654090 pc=0x4247c1]
goroutine 424 gp=0xc0014b0700 m=32 mp=0xc0013f8708 [running]:
runtime.throw({0x1b1a72d?, 0x73ea5bf5cb38?})
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/panic.go:1067 +0x48 fp=0xc003cb0f70 sp=0xc003cb0f40 pc=0x48bac8
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/signal_unix.go:931 +0x26c fp=0xc003cb0fd0 sp=0xc003cb0f70 pc=0x48dd6c
runtime.buildTypeAssertCache.func1(...)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:532
runtime.buildTypeAssertCache(0x18db2e0?, 0x1a8dd40, 0x0)
/opt/hostedtoolcache/go/1.23.6/x64/src/runtime/iface.go:544 +0x141 fp=0xc003cb1018 …
```
=> feat(containerd): retry cri unix grpc connection until ready

components/accelerator/nvidia/remapped-rows/component.go, components/info/component.go, components/info/component_test.go, components/kubelet/pod/component_test.go, components/memory/component.go, components/memory/component_test.go
=> feat(components): add missing nil pointer checks for getStates

components/library/component.go, components/library/component_test.go, components/library/id/id.go, pkg/config/default.go, pkg/server/server.go
=> feat(component/library): simplify + increase unit test coverage

pkg/server/server.go
=> fix(server): do not prematurely shutdown nvml instance for row remapping component

.goreleaser_darwin_amd64.yaml, .goreleaser_darwin_arm64.yaml, .goreleaser_linux_amd64.yaml, .goreleaser_linux_amd64_amzn2.yaml, .goreleaser_linux_amd64_amzn2023.yaml, .goreleaser_linux_amd64_ubuntu20.04.yaml, .goreleaser_linux_amd64_ubuntu22.04.yaml, .goreleaser_linux_amd64_ubuntu24.04.yaml, .goreleaser_linux_arm64_amzn2.yaml, .goreleaser_linux_arm64_amzn2023.yaml, .goreleaser_linux_arm64_ubuntu20.04.yaml, .goreleaser_linux_arm64_ubuntu22.04.yaml, .goreleaser_linux_arm64_ubuntu24.04.yaml
=> feat(goreleaser): remove deprecated fields

pkg/netutil/latency/edge/derp.go
=> fix(latency/derp): close ts client once used

components/docker/container/docker.go
=> fix(docker): close docker client once used

components/library/component.go, components/library/component_test.go
=> fix(library): sort reason slice to make /states more deterministic

components/accelerator/nvidia/remapped-rows/component.go, components/accelerator/nvidia/remapped-rows/component_test.go, components/containerd/pod/component.go, components/containerd/pod/component_test.go, components/cpu/component.go, components/cpu/component_test.go, components/docker/container/component.go, components/docker/container/component_test.go, components/fd/component.go, components/fd/component_test.go, components/info/component.go, components/info/component_test.go, components/kernel-module/component.go, components/kernel-module/component_test.go, components/kubelet/pod/component.go, components/kubelet/pod/component_test.go, components/memory/component.go, components/memory/component_test.go, components/tailscale/component.go, components/tailscale/component_test.go, pkg/session/serve.go
Replace: https://github.com/leptonai/gpud/pull/571
- **feat(memory): return error from data fetch**
- **feat(cpu): return data fetch error**
- **feat(fd): return data fetch error**
- **feat(info): return data fetch error**
- **feat(containerd): return error if found**
- **feat(remapped-rows): return data fetch error**
- **tailscale**
=> feat(fd, cpu, memory, remapped-rows, info, containerd, kubelet, docker, tailscale): return data fetch error

components/fd/component.go
=> nit(fd): remove unused prom gatherer from component

components/cpu/component.go
=> nit(cpu): remove unused prom gatherer from component

components/accelerator/nvidia/remapped-rows/component.go, components/accelerator/nvidia/remapped-rows/metrics/metrics.go, components/accelerator/nvidia/remapped-rows/metrics/metrics_test.go, components/cpu/component.go, components/cpu/metrics/metrics.go, components/disk/component_output.go, components/disk/metrics/metrics.go, components/fd/component.go, components/fd/metrics/metrics.go, components/fuse/component_output.go, components/fuse/metrics/metrics.go, components/memory/component.go, components/memory/metrics/metrics.go, components/network/latency/component_output.go, components/network/latency/metrics/metrics.go, e2e/e2e_test.go, pkg/metrics/scraper/prometheus_test.go, pkg/nvidia-query/metrics/clock-speed/metrics.go, pkg/nvidia-query/metrics/clock/metrics.go, pkg/nvidia-query/metrics/ecc/metrics.go, pkg/nvidia-query/metrics/gpm/metrics.go, pkg/nvidia-query/metrics/memory/metrics.go, pkg/nvidia-query/metrics/nvlink/metrics.go, pkg/nvidia-query/metrics/power/metrics.go, pkg/nvidia-query/metrics/processes/metrics.go, pkg/nvidia-query/metrics/temperature/metrics.go, pkg/nvidia-query/metrics/utilization/metrics.go, pkg/nvidia-query/nvml/gpm.go, pkg/nvidia-query/query.go
in prep for migrating to global metrics store
c.f., https://github.com/leptonai/gpud/pull/577
=> feat(metrics): label Prometheus metrics with component name

components/disk/component.go, components/disk/component_test.go
=> fix(disk): set missing State.Error field

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go, components/accelerator/nvidia/infiniband/id/id.go, components/accelerator/nvidia/infiniband/threshold.go, pkg/config/default.go, pkg/server/server.go, pkg/session/serve.go, pkg/session/serve_test.go
=> nits(infiniband): remove id package, make code ordering consistent

cmd/gpud/command/command.go, cmd/gpud/command/run.go, components/kubelet/pod/component.go, components/kubelet/pod/component_test.go, components/kubelet/pod/kubelet.go, pkg/config/config.go, pkg/config/default.go, pkg/config/options.go, pkg/config/options_test.go, pkg/netutil/netutil.go, pkg/netutil/netutil_test.go, pkg/server/server.go
=> feat(kubelet): check port open, list pods with failure threshold

pkg/gpud-manager/systemd/systemd.go, pkg/gpud-manager/systemd/systemd_test.go
=> feat(gpud-manager/systemd): auto-add --log-file flag with default file path

pkg/nvidia-query/xid/xid.go
=> feat(nvidia/xid): mark Xid 143 as fatal (gpu init failure)

cmd/gpud/command/login.go, pkg/login/gossip.go, pkg/login/gossip_test.go, pkg/login/login.go, pkg/login/login_test.go, pkg/server/server.go
=> feat(pkg/login): clean up, increase unit test coverage

components/accelerator/nvidia/clock-speed/metrics.go, components/accelerator/nvidia/ecc/metrics.go, components/accelerator/nvidia/gpm/metrics.go, components/accelerator/nvidia/hw-slowdown/metrics.go, components/accelerator/nvidia/memory/metrics.go, components/accelerator/nvidia/nvlink/metrics.go, components/accelerator/nvidia/power/metrics.go, components/accelerator/nvidia/processes/metrics.go, components/accelerator/nvidia/remapped-rows/metrics.go, components/accelerator/nvidia/temperature/metrics.go, components/accelerator/nvidia/utilization/metrics.go, components/cpu/metrics.go, components/disk/metrics.go, components/fd/metrics.go, components/fuse/metrics.go, components/info/component.go, components/memory/metrics.go, components/network/latency/metrics.go, pkg/gpud-metrics/metrics.go, pkg/gpud-state/state.go, pkg/metrics/registry.go, pkg/server/server.go, pkg/sqlite/metrics.go, pkg/sqlite/metrics_test.go
=> feat(metrics): define/use its own prometheus registry

components/accelerator/nvidia/bad-envs/component.go, components/accelerator/nvidia/bad-envs/component_test.go, components/accelerator/nvidia/nccl/component.go, components/accelerator/nvidia/nccl/component_test.go, components/accelerator/nvidia/processes/component.go, components/accelerator/nvidia/processes/component_test.go, components/accelerator/nvidia/xid/component_test.go, components/containerd/pod/component.go, components/containerd/pod/component_test.go, components/disk/component.go, components/disk/component_test.go, components/docker/container/component.go, components/docker/container/component_test.go, components/docker/container/docker_test.go, components/fuse/component.go, components/fuse/component_test.go, components/info/component.go, components/info/component_test.go, components/kernel-module/component.go, components/kernel-module/component_test.go, components/network/latency/component.go, components/network/latency/component_test.go, components/os/component.go, components/os/component_test.go, components/pci/component.go, components/pci/component_test.go, components/tailscale/component.go, components/tailscale/component_test.go
=> feat(components/*): increase unit test coverage, make healthy/reason check consistent

README.md
=> README: add test coverage codecov.io badge

components/memory/bpf.go, components/memory/bpf_test.go, components/memory/component.go, components/memory/component_test.go
=> tests(memory/bpf): add more unit tests

components/containerd/pod/component.go, components/containerd/pod/component_test.go, components/containerd/pod/cri.go, components/containerd/pod/cri_test.go
=> test(containerd/pod): add more unit tests

components/accelerator/nvidia/temperature/component.go
=> fix(nvidia): use correct temperature threshold in variable name

pkg/disk/disk.go
Fix https://github.com/leptonai/gpud/issues/408.
=> fix(disk): skip partition check if it does not exist anymore

components/accelerator/nvidia/temperature/component.go, components/os/component.go, components/os/component_test.go, components/types.go, pkg/diagnose/scan.go, pkg/nvidia-query/nvml/clock_events.go, pkg/nvidia-query/nvml/clock_events_test.go, pkg/nvidia-query/nvml/gpm.go, pkg/nvidia-query/nvml/instance.go, pkg/nvidia-query/nvml/instance_test.go, pkg/nvidia-query/nvml/lib/default.go, pkg/nvidia-query/nvml/lib/default_test.go, pkg/nvidia-query/nvml/lib/lib.go, pkg/nvidia-query/nvml/lib/lib_test.go, pkg/nvidia-query/nvml/nvml.go, pkg/process/process_additional_test.go
To get rid of a shared GPU fetch function in https://github.com/leptonai/gpud/blob/a37fbc23df80f827d4ef9d83206b6f580969182c/pkg/nvidia-query/query.go#L18-L24, and to support gossip API.
=> feat(os, nvidia, gpud scan): add "HealthCheckResult" interface to simplify scan per component

components/accelerator/nvidia/temperature/component.go, components/cpu/component.go, components/cpu/component_test.go, components/os/component.go, components/os/component_test.go, pkg/diagnose/scan.go
Address https://github.com/leptonai/gpud/issues/506.
=> feat(cpu): support one-off check health state (for "gpud scan")

components/memory/bpf.go, components/memory/component.go, components/memory/component_test.go, pkg/diagnose/scan.go
Address https://github.com/leptonai/gpud/issues/506.
=> feat(memory): add check health states helper for "gpud scan" operation

pkg/process/runner.go, pkg/process/runner_exclusive.go, pkg/process/runner_exclusive_test.go, pkg/session/serve.go, pkg/session/session.go
- **feat(process/scheduler): add exclusive scheduler**
- **feat(pkg/session): add "bootstrap" endpoint**
=> feat(process/scheduler): add exclusive scheduler, support "bootstrap" session message

components/registry.go, components/registry_test.go
=> feat(components): define registry interface for components init simplification

components/accelerator/nvidia/bad-envs/component.go, components/accelerator/nvidia/bad-envs/component_test.go, components/accelerator/nvidia/clock-speed/component.go, components/accelerator/nvidia/ecc/component.go, components/accelerator/nvidia/fabric-manager/component.go, components/accelerator/nvidia/gpm/component.go, components/accelerator/nvidia/gsp-firmware-mode/component.go, components/accelerator/nvidia/hw-slowdown/component.go, components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go, components/accelerator/nvidia/info/component.go, components/accelerator/nvidia/memory/component.go, components/accelerator/nvidia/nccl/component.go, components/accelerator/nvidia/nvlink/component.go, components/accelerator/nvidia/peermem/component.go, components/accelerator/nvidia/persistence-mode/component.go, components/accelerator/nvidia/power/component.go, components/accelerator/nvidia/processes/component.go, components/accelerator/nvidia/remapped-rows/component.go, components/accelerator/nvidia/sxid/component.go, components/accelerator/nvidia/temperature/component.go, components/accelerator/nvidia/utilization/component.go, components/accelerator/nvidia/xid/component.go
=> feat(nvidia/bad-envs): refactor to support one-off checks

components/containerd/pod/component.go, components/containerd/pod/component_test.go, components/docker/container/component.go, components/docker/container/component_test.go, components/kubelet/pod/component.go, components/kubelet/pod/component_test.go
=> feat(kubelet, containerd, docker): refactor to support one-off checks

components/tailscale/component.go, components/tailscale/component_test.go
=> feat(tailscale): refactor to support one-off checks

components/fd/component.go, components/fd/component_test.go
=> feat(fd): refactor to support one-off checks

components/fuse/component.go, components/fuse/component_test.go
=> feat(fuse): refactor to support one-time checks

components/kernel-module/component.go, components/kernel-module/component_test.go, components/registry.go
=> feat(kernel-modules): refactor to support one-time checks

components/pci/component.go, components/pci/component_test.go
=> feat(pci): refactor to support one-time checks

components/info/component.go, components/info/component_test.go, components/registry.go
=> feat(info): refactor to support one-time operations

components/memory/component.go, components/memory/component_test.go
=> feat(memory): refactor to support one-time checks

components/network/latency/component.go, components/network/latency/component_test.go, pkg/scan/scan.go, pkg/server/server.go
=> feat(network/latency): refactor to support one-time checks

components/cpu/component.go, components/cpu/component_test.go
=> feat(cpu): refactor to support one-time checks

components/library/component.go, components/library/component_test.go, components/registry.go
=> feat(components/library): refactor to support one-time operations

cmd/gpud/command/run.go
regresson from https://github.com/leptonai/gpud/pull/641
=> fix(gpud run): create metadata table if not exists

components/containerd/pod/cri_test.go
Progress towards https://github.com/leptonai/gpud/issues/472
=> Improve connect test coverage

components/accelerator/nvidia/bad-envs/component.go, components/accelerator/nvidia/bad-envs/component_test.go
=> feat(nvidia/bad-envs): rename Data to checkResult, add more unit tests

client/v1/healthz_test.go
Cherry-picked from https://github.com/leptonai/gpud/pull/627.
=> test(client/v1): add more healthz client tests

.gitignore, cmd/gpud/command/join.go, cmd/gpud/command/notify.go, cmd/gpud/command/up.go, pkg/gossip/client.go, pkg/gossip/client_test.go, pkg/gpud-manager/systemd/systemd.go, pkg/gpud-manager/systemd/systemd_test.go, pkg/login/client.go, pkg/login/client_test.go
=> feat(gpud): clean up --endpoint flag parsing, persist in systemd service file

pkg/server/handlers_test.go, pkg/server/middleware_test.go, pkg/server/server_test.go
Continued progress towards https://github.com/leptonai/gpud/issues/472
=> Add testing for pkg/server

e2e/e2e_test.go
Cherry-picked from https://github.com/leptonai/gpud/pull/627.
=> test(e2e): rename import aliases, context variables

components/registry.go, components/registry_test.go, components/types.go
Cherry-picked from https://github.com/leptonai/gpud/pull/627.
=> feat(components): add more register methods, add Deregisterable interface

client/v1/v1.go, client/v1/v1_test.go, e2e/e2e_test.go, pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go, pkg/custom-plugins/doc.go, pkg/custom-plugins/testdata/plugins.base64.yaml, pkg/custom-plugins/testdata/plugins.plaintext.yaml, pkg/custom-plugins/type_plugin.go, pkg/custom-plugins/type_plugin_test.go, pkg/custom-plugins/type_run_bash_script.go, pkg/custom-plugins/type_run_bash_script_test.go, pkg/custom-plugins/type_spec.go, pkg/custom-plugins/type_spec_test.go, pkg/custom-plugins/type_step.go, pkg/custom-plugins/type_step_test.go, pkg/custom-plugins/types.go, pkg/custom-plugins/utils.go, pkg/custom-plugins/utils_test.go, pkg/server/handlers_components.go, pkg/session/serve.go
Address https://github.com/leptonai/gpud/issues/568.
Some inspiration from https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-schemas-features.html.
=> feat(custom-plugins): implement server + client

components/accelerator/nvidia/fabric-manager/component.go, components/accelerator/nvidia/fabric-manager/component_test.go, components/accelerator/nvidia/info/component.go, components/accelerator/nvidia/info/component_test.go
=> fix(nvidia/info, fabric manager): check nvml library exists

pkg/server/server.go
=> fix(server): pre-process endpoint URL for new server

components/accelerator/nvidia/fabric-manager/component.go, components/accelerator/nvidia/fabric-manager/component_test.go
=> fix(fabric-manager): skip fabric manager check if it's not supported

components/fd/component.go, components/fd/component_test.go
=> feat(fd): clean up check error set, make reason message more static

client/v1/v1_test.go, e2e/e2e_test.go, pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go, pkg/custom-plugins/output_state.go, pkg/custom-plugins/output_state_test.go, pkg/custom-plugins/type_plugin_test.go, pkg/custom-plugins/type_spec.go, pkg/custom-plugins/type_spec_test.go, pkg/custom-plugins/types.go, pkg/custom-plugins/utils.go, pkg/custom-plugins/utils_test.go
Address https://github.com/leptonai/gpud/issues/568.
=> feat(custom-plugins): support custom health state in custom plugin

api/v1/types.go, pkg/machine-info/machine_info.go
=> feat(machine-info): add gpudVersion to machine info

cmd/gpud/command/up.go
=> feat(gpud up): run "login" first if token is provided

components/cpu/component.go, components/cpu/cpuinfo.go, pkg/machine-info/machine_info.go
=> feat(components): add go_arch

client/v1/v1_test.go, e2e/e2e_test.go, pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go, pkg/custom-plugins/testdata/plugins.base64.yaml, pkg/custom-plugins/testdata/plugins.plaintext.0.yaml, pkg/custom-plugins/testdata/plugins.plaintext.1.yaml, pkg/custom-plugins/type_plugin_test.go, pkg/custom-plugins/type_run_bash_script_test.go, pkg/custom-plugins/type_spec.go, pkg/custom-plugins/type_spec_test.go, pkg/custom-plugins/types.go
=> nit(external-plugins): rename/clarify state plugin is for HealthState

pkg/nvidia-query/nvml/gpu_product_name.go, pkg/nvidia-query/nvml/gpu_product_name_test.go, pkg/nvidia-query/nvml/instance.go
As in https://github.com/NVIDIA/k8s-device-plugin/blob/main/internal/lm/resource.go#L187-L204.
Fix https://github.com/leptonai/gpud/issues/388.
=> feat(nvidia-query/nvml): sanitize gpu product name

pkg/server/server.go
=> fix(session): add missing components registry

cmd/gpud/command/login.go
=> feat(login): remove server wait for login

cmd/gpud/command/login.go
=> fix(gpud login): use write mode to create first db file, create missing table

pkg/server/server.go
=> fix(server): check debuggable output for init plugin

pkg/process/process.go, pkg/process/process_additional_test.go, pkg/process/read_test.go, pkg/process/utils_test.go
=> nit(pkg/process): remove unused labels method

pkg/process/process_additional_test.go
=> fix(pkg/process): remove broken unit tests

api/v1/gossip.go, api/v1/login.go, api/v1/types.go, pkg/login/client_test.go, pkg/machine-info/login_request.go, pkg/machine-info/machine_info.go
=> feat(machine-info): reorganize machine info struct fields

components/network/latency/component_test.go
=> test(network-latency): 100% unit test coverage

components/fuse/component_test.go
=> test(fuse): add more unit tests

api/v1/types.go, components/accelerator/nvidia/info/component.go, components/accelerator/nvidia/info/component_test.go, pkg/machine-info/machine_info.go, pkg/nvidia-query/nvml/gpu_ids.go, pkg/nvidia-query/nvml/lib/mock/mock.go, pkg/nvidia-query/nvml/testutil/util.go
- **feat(machine-info): populate more gpu info (sn, minor id)**
- **feat(nvidia/info): track gpu ids**
=> feat(machine-info, nvidia/info): populate more gpu info (sn, minor id)

api/v1/types.go, e2e/e2e_test.go, pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go
=> feat(api/v1/types): add run_mode to HealthState

components/os/component.go, components/os/component_test.go, pkg/process/pids.go, pkg/process/pids_test.go
=> feat(os, pkg/process): increase test coverage for process package

components/disk/component.go, components/disk/component_test.go, components/fd/component.go, components/fuse/component.go, components/fuse/component_test.go, components/pci/component.go
=> feat(disk, fd, fuse, pci): simplify reason field message

components/cpu/component.go, components/cpu/component_test.go, components/memory/component.go, components/memory/component_test.go
=> feat(cpu, memory): make reason field message more static

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go
=> feat(nvidia/infiniband): make reason field message more static

components/accelerator/nvidia/nccl/component.go, components/accelerator/nvidia/nccl/component_test.go, components/accelerator/nvidia/nvlink/component.go, components/accelerator/nvidia/nvlink/component_test.go
=> feat(nvidia/nccl, nvlink): make reason field message more static

components/accelerator/nvidia/sxid/component.go, components/accelerator/nvidia/xid/component.go
=> feat(nvidia/xid,sxid): make reason field message more static

components/accelerator/nvidia/hw-slowdown/component.go, components/accelerator/nvidia/hw-slowdown/component_test.go
=> feat(nvidia/hw-slowdown): make reason field message more static

components/accelerator/nvidia/gpm/component.go, components/accelerator/nvidia/gpm/component_test.go, components/accelerator/nvidia/memory/component.go, components/accelerator/nvidia/memory/component_test.go, components/accelerator/nvidia/peermem/component.go, components/accelerator/nvidia/peermem/component_test.go
=> feat(nvidia/gpm, peermem, memory): make reason field message more static

cmd/gpud/command/login.go, pkg/gossip/client.go, pkg/login/client.go
=> feat(login, gossip): log at debug level

api/v1/types.go, components/disk/component.go, pkg/disk/findmnt.go, pkg/disk/findmnt_test.go, pkg/machine-info/machine_info.go, pkg/scan/scan.go
```
✔ machine info
+---------------------------+---------------------------------+
|       GPUd Version        |             v0.4.9              |
|       CUDA Version        |              12.2               |
| Container Runtime Version |      containerd://v1.7.20       |
|      Kernel Version       |       5.15.0-113-generic        |
|         OS Image          |       Ubuntu 22.04.4 LTS        |
|    Container Root Disk    | /dev/mapper/lepton_vg-lepton_lv |
|    GPU Driver Version     |           535.183.01            |
|        GPU Product        |      NVIDIA-A100-SXM4-80GB      |
|     GPU Manufacturer      |                                 |
|        GPU Memory         |           85899345920           |
+---------------------------+---------------------------------+
```
=> feat(machine-info): include container root disk device name, machine info in "gpud scan"

components/info/component.go, components/kernel-module/component.go, components/kernel-module/component_test.go, components/os/component.go, components/os/component_test.go
=> feat(os, kernel, info): make reason field message more static

components/accelerator/nvidia/gsp-firmware-mode/component.go, components/accelerator/nvidia/gsp-firmware-mode/component_test.go, components/accelerator/nvidia/persistence-mode/component.go, components/accelerator/nvidia/persistence-mode/component_test.go
=> feat(nvidia/gsp, persistence mode): make reason field message more static

pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go
=> feat(pkg/custom-plugins): make reason field message more static

components/network/latency/component.go, components/tailscale/component.go, components/tailscale/component_test.go
=> feat(network, tailscale): simplify reason field message

components/accelerator/nvidia/xid/component.go
=> fix(nvidia/xid): set unhealthy state if any critical errors are found in gpud scan

pkg/server/server.go
=> feat(server): refactor to use goroutines

components/fuse/component.go
=> fix(components/fuse): fix check results table printer header

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go, components/accelerator/nvidia/nccl/component_test.go
Address https://github.com/leptonai/gpud/issues/472
=> tests(nvidia/nccl): increase the unit test coverage

docs/ARCHITECTURE.md, docs/COMPONENTS.md
=> fix(docs): fix/remove broken links

components/disk/component.go, components/disk/component_test.go
=> fix(components/disk): retries on findmnt failures for invalid inputs

components/disk/component.go, pkg/machine-info/machine_info.go
=> feat(disk): track raid devices

api/v1/types_test.go, client/v1/v1_plugin_test.go, client/v1/v1_read_helpers_test.go, client/v1/v1_read_test.go, client/v1/v1_register_test.go, client/v1/v1_trigger_test.go, pkg/fuse/fuse.go, pkg/fuse/fuse_test.go, pkg/gpud-manager/controllers/package_controller_test.go, pkg/machine-info/machine_info_test.go, pkg/server/handlers_components_test.go, pkg/server/handlers_test.go, pkg/server/handlers_testutils_test.go, pkg/server/server.go, pkg/server/server_test.go, pkg/session/serve.go, pkg/session/serve_test.go
Just more unit tests based on the code that we have.
Next would be bigger refactoring on session/server/cmd* code base (after 0.5 release).
=> tests(pkg/server,session, api/v1, controllers, client, machine-info, fuse): more unit tests

components/accelerator/nvidia/infiniband/component.go, components/accelerator/nvidia/infiniband/component_test.go, pkg/nvidia-query/infiniband/ibstat.go
=> feat(nvidia/infiniband): reset error if partial ibstat output is found

pkg/gpud-manager/systemd/gpud.service
=> feat(gpud.service): restart gpud always

components/accelerator/nvidia/fabric-manager/log_watcher.go, pkg/kmsg/watcher.go
=> feat(kmsg, fabric-manager): set debug logs for deduper

api/v1/types.go, components/accelerator/nvidia/info/component_test.go, pkg/machine-info/machine_info.go, pkg/nvidia-query/nvml/gpu_ids.go, pkg/nvidia-query/nvml/gpu_ids_test.go, pkg/nvidia-query/nvml/lib/mock/mock.go, pkg/nvidia-query/nvml/testutil/util.go
=> feat(nvidia/accelerator): include GPU board ID in gpu info

components/accelerator/nvidia/clock-speed/metrics.go, components/accelerator/nvidia/ecc/metrics.go, components/accelerator/nvidia/gpm/metrics.go, components/accelerator/nvidia/hw-slowdown/metrics.go, components/accelerator/nvidia/memory/metrics.go, components/accelerator/nvidia/nvlink/metrics.go, components/accelerator/nvidia/power/metrics.go, components/accelerator/nvidia/processes/metrics.go, components/accelerator/nvidia/remapped-rows/metrics.go, components/accelerator/nvidia/temperature/metrics.go, components/accelerator/nvidia/utilization/metrics.go, components/cpu/metrics.go, components/disk/metrics.go, components/fuse/metrics.go, components/memory/metrics.go, components/network/latency/metrics.go, components/os/component_test.go, components/os/metrics.go
=> feat(metrics): fix/simplify file descriptor metrics labels

components/disk/component_test.go, pkg/gpud-manager/informer/file_informer.go, pkg/gpud-manager/informer/file_informer_test.go, pkg/scan/options_test.go, pkg/scan/scan.go, pkg/scan/scan_test.go, pkg/update/download_test.go, pkg/update/param.go, pkg/update/system_test.go, pkg/update/update.go, pkg/update/update_test.go
=> tests(pkg/update, scan): add more unit tests

cmd/gpud/command/status.go, pkg/process/pids.go, pkg/process/pids_find_process_test.go, pkg/process/pids_test.go
=> fix(gpud status): support non-systemd mode

cmd/gpud/command/command.go, cmd/gpud/command/custom-plugins.go, pkg/custom-plugins/execute.go, pkg/custom-plugins/execute_test.go
=> feat(gpud custom-plugins): add fail-fast option (exit immediately if any plugin returns unhealthy state)

pkg/eventstore/database.go, pkg/metrics/store/sqlite.go
=> nits(eventstore, sqlite): unexport column names

api/v1/types.go, components/accelerator/nvidia/hw-slowdown/component.go, components/accelerator/nvidia/xid/helper.go, components/accelerator/nvidia/xid/helper_test.go, pkg/nvidia-query/sxid/sxid.go, pkg/nvidia-query/sxid/sxid_test.go, pkg/nvidia-query/xid/xid.go, pkg/nvidia-query/xid/xid_test.go
Fix https://github.com/leptonai/gpud/issues/391.
=> feat(nvidia/xid, sxid): remove deprecated suggested action fields, update error message 

pkg/sqlite/sqlite.go, pkg/sqlite/sqlite_test.go
to help with refactoring /cmd code
=> feat(pkg/sqlite): add RunCompact helper

cmd/common/doc.go, cmd/common/terminal.go, cmd/gpud/command/command.go, cmd/gpud/command/compact.go, cmd/gpud/command/custom-plugins.go, cmd/gpud/command/down.go, cmd/gpud/command/join.go, cmd/gpud/command/login.go, cmd/gpud/command/status.go, cmd/gpud/command/up.go, pkg/scan/scan.go, pkg/scan/scan_test.go
to help refactor cmd/ directory
=> feat(gpud/cmd/common): define common terminal colors

components/cpu/component_test.go
=> fix(cpu): fix test cases from removed cpu info fields

cmd/gpud/command/command.go, cmd/gpud/command/join.go, cmd/gpud/command/up.go, pkg/containerd/cri.go, pkg/gpud-state/utils.go, pkg/netutil/latency/edge/derp.go, pkg/nvidia-query/nvml/instance.go
- **feat(gpud up/join): reduce noise in logs**
- **remove default**
=> feat(gpud join): reduce noise in logs

pkg/release/distsign/distsign.go, pkg/server/server.go, pkg/server/server_test.go, pkg/session/session.go, pkg/session/session_test.go
=> fix(server, session): fix local healthz check addr

api/v1/types.go, cmd/gpud/command/login.go, pkg/machine-info/gossip_request.go, pkg/machine-info/gossip_request_test.go, pkg/machine-info/login_request.go, pkg/machine-info/login_request_test.go, pkg/machine-info/machine_info.go, pkg/machine-info/machine_info_test.go, pkg/netutil/private_ip.go
=> feat(machine-info): include private IP device info

README.md
=> doc(README): explain how to install a specific version

api/v1/join.go, cmd/gpud/command/join.go
=> feat(api/v1): add separate JoinRequest/Response struct

pkg/httputil/httputil.go, pkg/httputil/httputil_test.go, pkg/server/server.go
Split from https://github.com/leptonai/gpud/pull/819.
=> feat(httputil): add CreateURL helper

cmd/gpud/command/command.go, cmd/gpud/command/compact.go, cmd/gpud/command/join.go, cmd/gpud/command/login.go, cmd/gpud/command/notify.go, cmd/gpud/command/status.go, cmd/gpud/command/up.go
=> fix(cmd/gpud): add missing --log-level flags

e2e/e2e_test.go
Split from https://github.com/leptonai/gpud/pull/819.
=> fix(e2e): block until test server is ready

cmd/gpud/command/up.go
=> nit(cmd/gpud/up): remove outdated print lines

cmd/gpud/command/command.go, cmd/gpud/scan/scan.go
Continue addressing https://github.com/leptonai/gpud/issues/472.
=> feat(cmd/gpud/scan): separate directory for "gpud scan"

api/v1/notification.go, cmd/gpud/command/command.go, cmd/gpud/custom-plugins/command.go, cmd/gpud/list-plugins/command.go, cmd/gpud/list-plugins/command_test.go, cmd/gpud/notify/command.go, cmd/gpud/run-plugin-group/command.go, cmd/gpud/run-plugin-group/command_test.go
To address https://github.com/leptonai/gpud/issues/472. Separate code as much as possible out of `cmd`.
=> feat(api/v1, cmd/gpud/notify/custom,list-plugins,run-plugin-group): add notification types, move "gpud notify" to a separate directory

cmd/gpud/command/join.go, cmd/gpud/command/up.go, cmd/gpud/down/command.go, cmd/gpud/login/command.go, pkg/osutil/osutil.go, pkg/osutil/osutil_test.go, pkg/update/system.go, pkg/update/system_test.go, pkg/update/update.go
Replace https://github.com/leptonai/gpud/pull/837.
=> feat(cmd/gpud): require sudo for join, up, down, login

cmd/gpud/command/join.go
=> nits(gpud join): clean up interactive message

cmd/gpud/command/command.go, cmd/gpud/run/command.go
Continue preparing for https://github.com/leptonai/gpud/issues/472.
=> feat(cmd/gpud): move run command to run/command.go

pkg/gossip/client.go, pkg/gossip/client_test.go, pkg/login/client.go, pkg/login/client_test.go
Split from https://github.com/leptonai/gpud/pull/819
=> feat(login, gossip): use httputil to create URLs

components/accelerator/nvidia/remapped-rows/component.go, components/accelerator/nvidia/remapped-rows/component_test.go
=> feat(nvidia/remapped-rows): add suggested actions for row remapping failure and pending

cmd/gpud/command/command.go, cmd/gpud/up/command.go
Continue to help with https://github.com/leptonai/gpud/issues/472.
=> feat(cmd/gpud): move "gpud up" to its own directory

cmd/gpud/command/command.go, cmd/gpud/join/command.go, cmd/gpud/notify/command.go
=> feat(cmd/gpud): move "join" command to a separate package

cmd/gpud/login/command.go, cmd/gpud/main.go, cmd/gpud/up/command.go, pkg/gossip/client.go, pkg/gossip/client_test.go, pkg/login/client.go, pkg/login/client_test.go
=> feat(login, gossip): better error message for status code

pkg/gpud-manager/systemd/systemd_test.go
=> fix(pkg/gpud-manager/systemd): fix unit tests

pkg/host/event.go, pkg/host/event_test.go
=> fix(host/reboot): handle stale timestamp when recording reboots in db

client/v1/v1.go, client/v1/v1_trigger_test.go, e2e/e2e_test.go, pkg/server/handlers_components.go, pkg/server/handlers_components_test.go, pkg/session/serve.go, pkg/session/serve_test.go
Replace https://github.com/leptonai/gpud/pull/852.
=> feat(session): support tag_name in "triggerComponentCheck"

cmd/gpud/command/command.go, cmd/gpud/run/command.go, components/all/all.go, pkg/config/config.go, pkg/scan/scan.go, pkg/server/server.go
To select components to enable.
Default will be enabling all.
=> feat(gpud run): add "--enable-components" flag (optional)

cmd/gpud/join/command.go
=> fix(gpud join): use get provider name function

cmd/gpud/machine-info/command.go, pkg/providers/azure/imds/imds.go
=> fix(gpud machine-info): print machine-id first, warning iff "AzurePublicCloud"

pkg/eventstore/database.go
=> nit(pkg/eventstore): lower noise in db close

pkg/netutil/latency/edge/derpmap/derpmap.json
=> feat(edge/derpmap): add more derp server in Frankfurt

cmd/gpud/machine-info/command.go
=> fix(cmd/machine-info): do not read machine id if not logged in

docs/PLUGIN.md, pkg/custom-plugins/component.go, pkg/custom-plugins/plugin_output.go, pkg/custom-plugins/plugin_output_test.go, pkg/custom-plugins/types.go
Create ability to log plugin outputs via the new log_path option.
=> Log plugin output with path substitution

cmd/gpud/join/command.go, cmd/gpud/login/command.go, cmd/gpud/up/command.go
=> debug(cmd/gpud): add debug logs for login, up, join (in case too slow)

install.sh
=> fix(install.sh): remove temporal directory in case of previous installation failure

cmd/gpud/command/command.go, cmd/gpud/run/command.go, pkg/config/config.go, pkg/server/server.go
=> nit(gpud): remove enable-fault-injector flag

cmd/gpud/command/command.go, pkg/custom-plugins/custom_plugins.go, pkg/custom-plugins/spec.go, pkg/custom-plugins/spec_test.go, pkg/server/handlers_components_test.go, pkg/server/handlers_plugins_test.go, pkg/server/server.go, pkg/session/serve.go, pkg/session/serve_plugins.go, pkg/session/serve_plugins_test.go, pkg/session/serve_test.go, pkg/session/session.go
Split from https://github.com/leptonai/gpud/pull/871/.
=> feat(pkg/session): support setPluginSpecs session API

client/v1/v1_plugins_test.go, cmd/gpud/custom-plugins/command.go, cmd/gpud/list-plugins/command.go, cmd/gpud/list-plugins/command_test.go, e2e/e2e_test.go, pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go, pkg/custom-plugins/execute.go, pkg/custom-plugins/plugin_test.go, pkg/custom-plugins/run_bash_script_test.go, pkg/custom-plugins/spec.go, pkg/custom-plugins/spec_test.go, pkg/custom-plugins/testdata/plugins.base64.yaml, pkg/custom-plugins/testdata/plugins.manual.yaml, pkg/custom-plugins/testdata/plugins.plaintext.0.yaml, pkg/custom-plugins/testdata/plugins.plaintext.1.yaml, pkg/custom-plugins/testdata/plugins.plaintext.2.regex.yaml, pkg/custom-plugins/types.go, pkg/server/handlers_plugins_test.go, pkg/server/server.go, pkg/session/serve_plugins_test.go
To be consistent, and ensures its compatibility with the old spec format.
=> feat(custom-plugins): rename "type" to "plugin_type"

pkg/custom-plugins/spec.go, pkg/custom-plugins/spec_test.go, pkg/server/server.go
=> fix(custom-plugins): handle deprecated "Plugin.type" when loading specs

api/v1/types.go, pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go
=> feat(api/v1): add "HealthState.RawOutput" for custom plugins

pkg/custom-plugins/component.go, pkg/custom-plugins/component_test.go
=> fix(custom-plugins): include tags from spec

pkg/nvidia-query/xid/xid.go
=> fix typos in xid.go

api/v1/login.go, cmd/gpud/login/command.go
- add ValidationResults field to LoginResponse
- print validation results in login command
=> feat(login): add validation results to login response

cmd/gpud/join/command.go
=> fix(gpud join): use private-ip flag if provided

pkg/disk/disk_partition_usage_test.go, pkg/disk/options.go
=> feat(pkg/disk): match more nfs fs type with prefix

pkg/gpud-manager/controllers/package_controller.go
=> feat(pkg/gpud-manager): make package controller logs less noisy

components/os/component.go, components/os/component_test.go
=> feat(os): add suggested actions for "too many zombie processes", other file descriptor states

components/accelerator/nvidia/nvlink/component.go, components/accelerator/nvidia/nvlink/component_test.go, components/accelerator/nvidia/nvlink/metrics.go, pkg/nvidia-query/nvml/nvlink.go, pkg/nvidia-query/nvml/nvlink_test.go
=> fix(nvidia/nvlink): fix typo in metrics name

components/accelerator/nvidia/gsp-firmware-mode/component.go, components/accelerator/nvidia/gsp-firmware-mode/component_test.go
=> feat(nvidia/gsp-firmware-mode): degraded when GSP firmware mode is supported/enabled

pkg/nvidia-query/nvml/lib/default.go
=> fix(nvidia-query): handle "Driver Not Loaded" error

components/accelerator/nvidia/sxid/component.go, components/accelerator/nvidia/sxid/component_test.go, components/accelerator/nvidia/xid/component.go, components/accelerator/nvidia/xid/component_test.go, components/docker/component.go
- add getError() to checkResult
- fix err.Error() panic in nvidia/xid, nvidia/sxid, docker
=> fix(nvidia/xid, nvidia/sxid, docker): fix err.Error() panic

components/accelerator/nvidia/infiniband/kmsg_matcher_test.go, components/cpu/kmsg_matcher_test.go, components/disk/kmsg_matcher_test.go, components/library/component_test.go, components/memory/bpf_test.go
=> tests(components): use assert for unit tests

pkg/nvidia-query/xid/xid.go
=> feat(nvidia/xid): xid 110 should suggest reboot first

components/memory/component.go, components/memory/kmsg_matcher.go, components/memory/kmsg_matcher_test.go
ref.
https://github.com/google/cadvisor/blob/master/utils/oomparser/oomparser_test.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/oom/oom_watcher_linux.go
=> feat(memory): make oom events human readable using cadvisor code

pkg/disk/options.go, pkg/disk/options_test.go
- **feat(update): use auto-update-exit-code for systemd managed gpud updates**
- **fix(pkg/disk): match virtiofs as nfs**
=> fix(pkg/disk): match virtiofs as nfs

client/v1/v1.go, cmd/gpud/notify/command.go, pkg/kubelet/kubelet.go, pkg/login/client.go, pkg/netutil/public_ip.go
=> [LEP-1206] feat(http): add proxy support for clients

components/nfs/component.go, components/nfs/component_test.go
=> feat(nfs): improve error message

cmd/gpud/command/command.go, cmd/gpud/common/parse.go, cmd/gpud/common/parse_test.go, cmd/gpud/run/command.go, cmd/gpud/scan/command.go, components/accelerator/nvidia/remapped-rows/component.go, components/accelerator/nvidia/remapped-rows/component_test.go, components/registry.go, components/registry_test.go, pkg/config/config.go, pkg/config/default.go, pkg/config/options.go, pkg/config/options_test.go, pkg/scan/options.go, pkg/scan/options_test.go, pkg/scan/scan.go, pkg/server/server.go
=> [LEP-1218] feat(row-remapping): inject failure by uuid (optional)

cmd/gpud/machine-info/command.go
=> [LEP-1383] fix(cmd/machine-info): show provider private IP from network info

cmd/gpud/command/command.go, cmd/gpud/run/command.go, pkg/config/config.go, pkg/server/server.go, pkg/update/update.go, pkg/update/version_file.go, pkg/update/version_file_test.go
=> [LEP-1422] feat(update): add version file for auto update

README.md, contrib/helm-example/gpud/values.yaml, docs/INSTALL.md, docs/TUTORIALS.md
=> feat(release): bump up latest versions to v0.6.0

components/disk/component.go, components/disk/component_failure_resolution_test.go, components/disk/component_suggested_actions_test.go, components/disk/component_test.go
=> [LEP-1606] feat(disk): skip NFS checks if NFS configs are not set

cmd/gpud/status/command.go
=> [LEP-1679] fix(gpud/status): do not prompt tailing non-existent log files

pkg/gpud-manager/packages/packages.go, pkg/gpud-manager/packages/packages_test.go
=> [LEP-1803] fix(gpud-manager): fix progress bar display for uninstalled packages

pkg/custom-plugins/spec.go, pkg/custom-plugins/spec_test.go
Cherry-pick-ed from https://github.com/leptonai/gpud/pull/1051.
=> [LEP-1814] feat(custom-plugins): mark "no update" if both prev/new spec are none

components/accelerator/nvidia/gsp-firmware-mode/component.go, components/accelerator/nvidia/gsp-firmware-mode/component_test.go
=> [LEP-1875] feat(nvidia/gsp-firmware-mode): degrade if supported but not disabled

components/disk/component.go, components/disk/component_failure_resolution_test.go, components/disk/component_suggested_actions_test.go, components/disk/component_test.go, components/disk/kmsg_matcher.go, components/disk/kmsg_matcher_test.go
=> [LEP-1325] [LEP-1736] feat(disk): remove "no space left" event, add health state checks based on free space left

components/accelerator/nvidia/sxid/component.go, components/accelerator/nvidia/sxid/component_test.go, components/accelerator/nvidia/xid/component.go, components/accelerator/nvidia/xid/component_test.go
Fix https://github.com/leptonai/gpud/issues/1095.
=> fix(nvidia/xid,sxid): fix panic in gpud scan
